// Code generated by ent, DO NOT EDIT.

package zenxiangliyurecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldUserID, v))
}

// PlayDate applies equality check predicate on the "play_date" field. It's identical to PlayDateEQ.
func PlayDate(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldPlayDate, v))
}

// TicketAmount applies equality check predicate on the "ticket_amount" field. It's identical to TicketAmountEQ.
func TicketAmount(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldTicketAmount, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldRewardAmount, v))
}

// UserNetAmount applies equality check predicate on the "user_net_amount" field. It's identical to UserNetAmountEQ.
func UserNetAmount(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldUserNetAmount, v))
}

// SystemRevenue applies equality check predicate on the "system_revenue" field. It's identical to SystemRevenueEQ.
func SystemRevenue(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldSystemRevenue, v))
}

// SystemExpense applies equality check predicate on the "system_expense" field. It's identical to SystemExpenseEQ.
func SystemExpense(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldSystemExpense, v))
}

// SystemProfit applies equality check predicate on the "system_profit" field. It's identical to SystemProfitEQ.
func SystemProfit(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldSystemProfit, v))
}

// PrizeID applies equality check predicate on the "prize_id" field. It's identical to PrizeIDEQ.
func PrizeID(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldPrizeID, v))
}

// PrizeNameSnapshot applies equality check predicate on the "prize_name_snapshot" field. It's identical to PrizeNameSnapshotEQ.
func PrizeNameSnapshot(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldPrizeNameSnapshot, v))
}

// ProbabilitySnapshot applies equality check predicate on the "probability_snapshot" field. It's identical to ProbabilitySnapshotEQ.
func ProbabilitySnapshot(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldProbabilitySnapshot, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfterTicket applies equality check predicate on the "balance_after_ticket" field. It's identical to BalanceAfterTicketEQ.
func BalanceAfterTicket(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldBalanceAfterTicket, v))
}

// BalanceAfterReward applies equality check predicate on the "balance_after_reward" field. It's identical to BalanceAfterRewardEQ.
func BalanceAfterReward(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldBalanceAfterReward, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// PlayDateEQ applies the EQ predicate on the "play_date" field.
func PlayDateEQ(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldPlayDate, v))
}

// PlayDateNEQ applies the NEQ predicate on the "play_date" field.
func PlayDateNEQ(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldPlayDate, v))
}

// PlayDateIn applies the In predicate on the "play_date" field.
func PlayDateIn(vs ...time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldPlayDate, vs...))
}

// PlayDateNotIn applies the NotIn predicate on the "play_date" field.
func PlayDateNotIn(vs ...time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldPlayDate, vs...))
}

// PlayDateGT applies the GT predicate on the "play_date" field.
func PlayDateGT(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldPlayDate, v))
}

// PlayDateGTE applies the GTE predicate on the "play_date" field.
func PlayDateGTE(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldPlayDate, v))
}

// PlayDateLT applies the LT predicate on the "play_date" field.
func PlayDateLT(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldPlayDate, v))
}

// PlayDateLTE applies the LTE predicate on the "play_date" field.
func PlayDateLTE(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldPlayDate, v))
}

// TicketAmountEQ applies the EQ predicate on the "ticket_amount" field.
func TicketAmountEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldTicketAmount, v))
}

// TicketAmountNEQ applies the NEQ predicate on the "ticket_amount" field.
func TicketAmountNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldTicketAmount, v))
}

// TicketAmountIn applies the In predicate on the "ticket_amount" field.
func TicketAmountIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldTicketAmount, vs...))
}

// TicketAmountNotIn applies the NotIn predicate on the "ticket_amount" field.
func TicketAmountNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldTicketAmount, vs...))
}

// TicketAmountGT applies the GT predicate on the "ticket_amount" field.
func TicketAmountGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldTicketAmount, v))
}

// TicketAmountGTE applies the GTE predicate on the "ticket_amount" field.
func TicketAmountGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldTicketAmount, v))
}

// TicketAmountLT applies the LT predicate on the "ticket_amount" field.
func TicketAmountLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldTicketAmount, v))
}

// TicketAmountLTE applies the LTE predicate on the "ticket_amount" field.
func TicketAmountLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldTicketAmount, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldRewardAmount, v))
}

// UserNetAmountEQ applies the EQ predicate on the "user_net_amount" field.
func UserNetAmountEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldUserNetAmount, v))
}

// UserNetAmountNEQ applies the NEQ predicate on the "user_net_amount" field.
func UserNetAmountNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldUserNetAmount, v))
}

// UserNetAmountIn applies the In predicate on the "user_net_amount" field.
func UserNetAmountIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldUserNetAmount, vs...))
}

// UserNetAmountNotIn applies the NotIn predicate on the "user_net_amount" field.
func UserNetAmountNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldUserNetAmount, vs...))
}

// UserNetAmountGT applies the GT predicate on the "user_net_amount" field.
func UserNetAmountGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldUserNetAmount, v))
}

// UserNetAmountGTE applies the GTE predicate on the "user_net_amount" field.
func UserNetAmountGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldUserNetAmount, v))
}

// UserNetAmountLT applies the LT predicate on the "user_net_amount" field.
func UserNetAmountLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldUserNetAmount, v))
}

// UserNetAmountLTE applies the LTE predicate on the "user_net_amount" field.
func UserNetAmountLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldUserNetAmount, v))
}

// SystemRevenueEQ applies the EQ predicate on the "system_revenue" field.
func SystemRevenueEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldSystemRevenue, v))
}

// SystemRevenueNEQ applies the NEQ predicate on the "system_revenue" field.
func SystemRevenueNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldSystemRevenue, v))
}

// SystemRevenueIn applies the In predicate on the "system_revenue" field.
func SystemRevenueIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldSystemRevenue, vs...))
}

// SystemRevenueNotIn applies the NotIn predicate on the "system_revenue" field.
func SystemRevenueNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldSystemRevenue, vs...))
}

// SystemRevenueGT applies the GT predicate on the "system_revenue" field.
func SystemRevenueGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldSystemRevenue, v))
}

// SystemRevenueGTE applies the GTE predicate on the "system_revenue" field.
func SystemRevenueGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldSystemRevenue, v))
}

// SystemRevenueLT applies the LT predicate on the "system_revenue" field.
func SystemRevenueLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldSystemRevenue, v))
}

// SystemRevenueLTE applies the LTE predicate on the "system_revenue" field.
func SystemRevenueLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldSystemRevenue, v))
}

// SystemExpenseEQ applies the EQ predicate on the "system_expense" field.
func SystemExpenseEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldSystemExpense, v))
}

// SystemExpenseNEQ applies the NEQ predicate on the "system_expense" field.
func SystemExpenseNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldSystemExpense, v))
}

// SystemExpenseIn applies the In predicate on the "system_expense" field.
func SystemExpenseIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldSystemExpense, vs...))
}

// SystemExpenseNotIn applies the NotIn predicate on the "system_expense" field.
func SystemExpenseNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldSystemExpense, vs...))
}

// SystemExpenseGT applies the GT predicate on the "system_expense" field.
func SystemExpenseGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldSystemExpense, v))
}

// SystemExpenseGTE applies the GTE predicate on the "system_expense" field.
func SystemExpenseGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldSystemExpense, v))
}

// SystemExpenseLT applies the LT predicate on the "system_expense" field.
func SystemExpenseLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldSystemExpense, v))
}

// SystemExpenseLTE applies the LTE predicate on the "system_expense" field.
func SystemExpenseLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldSystemExpense, v))
}

// SystemProfitEQ applies the EQ predicate on the "system_profit" field.
func SystemProfitEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldSystemProfit, v))
}

// SystemProfitNEQ applies the NEQ predicate on the "system_profit" field.
func SystemProfitNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldSystemProfit, v))
}

// SystemProfitIn applies the In predicate on the "system_profit" field.
func SystemProfitIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldSystemProfit, vs...))
}

// SystemProfitNotIn applies the NotIn predicate on the "system_profit" field.
func SystemProfitNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldSystemProfit, vs...))
}

// SystemProfitGT applies the GT predicate on the "system_profit" field.
func SystemProfitGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldSystemProfit, v))
}

// SystemProfitGTE applies the GTE predicate on the "system_profit" field.
func SystemProfitGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldSystemProfit, v))
}

// SystemProfitLT applies the LT predicate on the "system_profit" field.
func SystemProfitLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldSystemProfit, v))
}

// SystemProfitLTE applies the LTE predicate on the "system_profit" field.
func SystemProfitLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldSystemProfit, v))
}

// PrizeIDEQ applies the EQ predicate on the "prize_id" field.
func PrizeIDEQ(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldPrizeID, v))
}

// PrizeIDNEQ applies the NEQ predicate on the "prize_id" field.
func PrizeIDNEQ(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldPrizeID, v))
}

// PrizeIDIn applies the In predicate on the "prize_id" field.
func PrizeIDIn(vs ...int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldPrizeID, vs...))
}

// PrizeIDNotIn applies the NotIn predicate on the "prize_id" field.
func PrizeIDNotIn(vs ...int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldPrizeID, vs...))
}

// PrizeIDGT applies the GT predicate on the "prize_id" field.
func PrizeIDGT(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldPrizeID, v))
}

// PrizeIDGTE applies the GTE predicate on the "prize_id" field.
func PrizeIDGTE(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldPrizeID, v))
}

// PrizeIDLT applies the LT predicate on the "prize_id" field.
func PrizeIDLT(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldPrizeID, v))
}

// PrizeIDLTE applies the LTE predicate on the "prize_id" field.
func PrizeIDLTE(v int64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldPrizeID, v))
}

// PrizeIDIsNil applies the IsNil predicate on the "prize_id" field.
func PrizeIDIsNil() predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIsNull(FieldPrizeID))
}

// PrizeIDNotNil applies the NotNil predicate on the "prize_id" field.
func PrizeIDNotNil() predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotNull(FieldPrizeID))
}

// PrizeNameSnapshotEQ applies the EQ predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotEQ(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotNEQ applies the NEQ predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotNEQ(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotIn applies the In predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotIn(vs ...string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldPrizeNameSnapshot, vs...))
}

// PrizeNameSnapshotNotIn applies the NotIn predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotNotIn(vs ...string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldPrizeNameSnapshot, vs...))
}

// PrizeNameSnapshotGT applies the GT predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotGT(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotGTE applies the GTE predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotGTE(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotLT applies the LT predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotLT(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotLTE applies the LTE predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotLTE(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotContains applies the Contains predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotContains(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldContains(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotHasPrefix applies the HasPrefix predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotHasPrefix(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldHasPrefix(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotHasSuffix applies the HasSuffix predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotHasSuffix(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldHasSuffix(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotEqualFold applies the EqualFold predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotEqualFold(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEqualFold(FieldPrizeNameSnapshot, v))
}

// PrizeNameSnapshotContainsFold applies the ContainsFold predicate on the "prize_name_snapshot" field.
func PrizeNameSnapshotContainsFold(v string) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldContainsFold(FieldPrizeNameSnapshot, v))
}

// ProbabilitySnapshotEQ applies the EQ predicate on the "probability_snapshot" field.
func ProbabilitySnapshotEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldProbabilitySnapshot, v))
}

// ProbabilitySnapshotNEQ applies the NEQ predicate on the "probability_snapshot" field.
func ProbabilitySnapshotNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldProbabilitySnapshot, v))
}

// ProbabilitySnapshotIn applies the In predicate on the "probability_snapshot" field.
func ProbabilitySnapshotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldProbabilitySnapshot, vs...))
}

// ProbabilitySnapshotNotIn applies the NotIn predicate on the "probability_snapshot" field.
func ProbabilitySnapshotNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldProbabilitySnapshot, vs...))
}

// ProbabilitySnapshotGT applies the GT predicate on the "probability_snapshot" field.
func ProbabilitySnapshotGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldProbabilitySnapshot, v))
}

// ProbabilitySnapshotGTE applies the GTE predicate on the "probability_snapshot" field.
func ProbabilitySnapshotGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldProbabilitySnapshot, v))
}

// ProbabilitySnapshotLT applies the LT predicate on the "probability_snapshot" field.
func ProbabilitySnapshotLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldProbabilitySnapshot, v))
}

// ProbabilitySnapshotLTE applies the LTE predicate on the "probability_snapshot" field.
func ProbabilitySnapshotLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldProbabilitySnapshot, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceAfterTicketEQ applies the EQ predicate on the "balance_after_ticket" field.
func BalanceAfterTicketEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldBalanceAfterTicket, v))
}

// BalanceAfterTicketNEQ applies the NEQ predicate on the "balance_after_ticket" field.
func BalanceAfterTicketNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldBalanceAfterTicket, v))
}

// BalanceAfterTicketIn applies the In predicate on the "balance_after_ticket" field.
func BalanceAfterTicketIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldBalanceAfterTicket, vs...))
}

// BalanceAfterTicketNotIn applies the NotIn predicate on the "balance_after_ticket" field.
func BalanceAfterTicketNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldBalanceAfterTicket, vs...))
}

// BalanceAfterTicketGT applies the GT predicate on the "balance_after_ticket" field.
func BalanceAfterTicketGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldBalanceAfterTicket, v))
}

// BalanceAfterTicketGTE applies the GTE predicate on the "balance_after_ticket" field.
func BalanceAfterTicketGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldBalanceAfterTicket, v))
}

// BalanceAfterTicketLT applies the LT predicate on the "balance_after_ticket" field.
func BalanceAfterTicketLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldBalanceAfterTicket, v))
}

// BalanceAfterTicketLTE applies the LTE predicate on the "balance_after_ticket" field.
func BalanceAfterTicketLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldBalanceAfterTicket, v))
}

// BalanceAfterRewardEQ applies the EQ predicate on the "balance_after_reward" field.
func BalanceAfterRewardEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldBalanceAfterReward, v))
}

// BalanceAfterRewardNEQ applies the NEQ predicate on the "balance_after_reward" field.
func BalanceAfterRewardNEQ(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldBalanceAfterReward, v))
}

// BalanceAfterRewardIn applies the In predicate on the "balance_after_reward" field.
func BalanceAfterRewardIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldBalanceAfterReward, vs...))
}

// BalanceAfterRewardNotIn applies the NotIn predicate on the "balance_after_reward" field.
func BalanceAfterRewardNotIn(vs ...float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldBalanceAfterReward, vs...))
}

// BalanceAfterRewardGT applies the GT predicate on the "balance_after_reward" field.
func BalanceAfterRewardGT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldBalanceAfterReward, v))
}

// BalanceAfterRewardGTE applies the GTE predicate on the "balance_after_reward" field.
func BalanceAfterRewardGTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldBalanceAfterReward, v))
}

// BalanceAfterRewardLT applies the LT predicate on the "balance_after_reward" field.
func BalanceAfterRewardLT(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldBalanceAfterReward, v))
}

// BalanceAfterRewardLTE applies the LTE predicate on the "balance_after_reward" field.
func BalanceAfterRewardLTE(v float64) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldBalanceAfterReward, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ZenxiangLiyuRecord) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ZenxiangLiyuRecord) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ZenxiangLiyuRecord) predicate.ZenxiangLiyuRecord {
	return predicate.ZenxiangLiyuRecord(sql.NotPredicates(p))
}
