// Code generated by ent, DO NOT EDIT.

package zenxiangliyurecord

import (
	"encoding/json/jsontext"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the zenxiangliyurecord type in the database.
	Label = "zenxiang_liyu_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlayDate holds the string denoting the play_date field in the database.
	FieldPlayDate = "play_date"
	// FieldTicketAmount holds the string denoting the ticket_amount field in the database.
	FieldTicketAmount = "ticket_amount"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldUserNetAmount holds the string denoting the user_net_amount field in the database.
	FieldUserNetAmount = "user_net_amount"
	// FieldSystemRevenue holds the string denoting the system_revenue field in the database.
	FieldSystemRevenue = "system_revenue"
	// FieldSystemExpense holds the string denoting the system_expense field in the database.
	FieldSystemExpense = "system_expense"
	// FieldSystemProfit holds the string denoting the system_profit field in the database.
	FieldSystemProfit = "system_profit"
	// FieldPrizeID holds the string denoting the prize_id field in the database.
	FieldPrizeID = "prize_id"
	// FieldPrizeNameSnapshot holds the string denoting the prize_name_snapshot field in the database.
	FieldPrizeNameSnapshot = "prize_name_snapshot"
	// FieldProbabilitySnapshot holds the string denoting the probability_snapshot field in the database.
	FieldProbabilitySnapshot = "probability_snapshot"
	// FieldConfigSnapshot holds the string denoting the config_snapshot field in the database.
	FieldConfigSnapshot = "config_snapshot"
	// FieldBalanceBefore holds the string denoting the balance_before field in the database.
	FieldBalanceBefore = "balance_before"
	// FieldBalanceAfterTicket holds the string denoting the balance_after_ticket field in the database.
	FieldBalanceAfterTicket = "balance_after_ticket"
	// FieldBalanceAfterReward holds the string denoting the balance_after_reward field in the database.
	FieldBalanceAfterReward = "balance_after_reward"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePrize holds the string denoting the prize edge name in mutations.
	EdgePrize = "prize"
	// Table holds the table name of the zenxiangliyurecord in the database.
	Table = "zenxiang_liyu_records"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "zenxiang_liyu_records"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// PrizeTable is the table that holds the prize relation/edge.
	PrizeTable = "zenxiang_liyu_records"
	// PrizeInverseTable is the table name for the ZenxiangLiyuPrize entity.
	// It exists in this package in order to avoid circular dependency with the "zenxiangliyuprize" package.
	PrizeInverseTable = "zenxiang_liyu_prizes"
	// PrizeColumn is the table column denoting the prize relation/edge.
	PrizeColumn = "prize_id"
)

// Columns holds all SQL columns for zenxiangliyurecord fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldUserID,
	FieldPlayDate,
	FieldTicketAmount,
	FieldRewardAmount,
	FieldUserNetAmount,
	FieldSystemRevenue,
	FieldSystemExpense,
	FieldSystemProfit,
	FieldPrizeID,
	FieldPrizeNameSnapshot,
	FieldProbabilitySnapshot,
	FieldConfigSnapshot,
	FieldBalanceBefore,
	FieldBalanceAfterTicket,
	FieldBalanceAfterReward,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// PrizeNameSnapshotValidator is a validator for the "prize_name_snapshot" field. It is called by the builders before save.
	PrizeNameSnapshotValidator func(string) error
	// DefaultConfigSnapshot holds the default value on creation for the "config_snapshot" field.
	DefaultConfigSnapshot func() jsontext.Value
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ZenxiangLiyuRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlayDate orders the results by the play_date field.
func ByPlayDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayDate, opts...).ToFunc()
}

// ByTicketAmount orders the results by the ticket_amount field.
func ByTicketAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketAmount, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByUserNetAmount orders the results by the user_net_amount field.
func ByUserNetAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserNetAmount, opts...).ToFunc()
}

// BySystemRevenue orders the results by the system_revenue field.
func BySystemRevenue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemRevenue, opts...).ToFunc()
}

// BySystemExpense orders the results by the system_expense field.
func BySystemExpense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemExpense, opts...).ToFunc()
}

// BySystemProfit orders the results by the system_profit field.
func BySystemProfit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemProfit, opts...).ToFunc()
}

// ByPrizeID orders the results by the prize_id field.
func ByPrizeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeID, opts...).ToFunc()
}

// ByPrizeNameSnapshot orders the results by the prize_name_snapshot field.
func ByPrizeNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeNameSnapshot, opts...).ToFunc()
}

// ByProbabilitySnapshot orders the results by the probability_snapshot field.
func ByProbabilitySnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbabilitySnapshot, opts...).ToFunc()
}

// ByBalanceBefore orders the results by the balance_before field.
func ByBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBefore, opts...).ToFunc()
}

// ByBalanceAfterTicket orders the results by the balance_after_ticket field.
func ByBalanceAfterTicket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfterTicket, opts...).ToFunc()
}

// ByBalanceAfterReward orders the results by the balance_after_reward field.
func ByBalanceAfterReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfterReward, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPrizeField orders the results by prize field.
func ByPrizeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrizeStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPrizeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrizeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrizeTable, PrizeColumn),
	)
}
