// Code generated by ent, DO NOT EDIT.

package zenxiangliyuprize

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldName, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldRewardAmount, v))
}

// Probability applies equality check predicate on the "probability" field. It's identical to ProbabilityEQ.
func Probability(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldProbability, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldContainsFold(FieldName, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldRewardAmount, v))
}

// ProbabilityEQ applies the EQ predicate on the "probability" field.
func ProbabilityEQ(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldProbability, v))
}

// ProbabilityNEQ applies the NEQ predicate on the "probability" field.
func ProbabilityNEQ(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldProbability, v))
}

// ProbabilityIn applies the In predicate on the "probability" field.
func ProbabilityIn(vs ...float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldProbability, vs...))
}

// ProbabilityNotIn applies the NotIn predicate on the "probability" field.
func ProbabilityNotIn(vs ...float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldProbability, vs...))
}

// ProbabilityGT applies the GT predicate on the "probability" field.
func ProbabilityGT(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldProbability, v))
}

// ProbabilityGTE applies the GTE predicate on the "probability" field.
func ProbabilityGTE(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldProbability, v))
}

// ProbabilityLT applies the LT predicate on the "probability" field.
func ProbabilityLT(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldProbability, v))
}

// ProbabilityLTE applies the LTE predicate on the "probability" field.
func ProbabilityLTE(v float64) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldProbability, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.FieldLTE(FieldSortOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ZenxiangLiyuPrize) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ZenxiangLiyuPrize) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ZenxiangLiyuPrize) predicate.ZenxiangLiyuPrize {
	return predicate.ZenxiangLiyuPrize(sql.NotPredicates(p))
}
