ALTER TABLE usage_logs
  ADD COLUMN IF NOT EXISTS e2e_first_token_ms INTEGER,
  ADD COLUMN IF NOT EXISTS routing_ms INTEGER,
  ADD COLUMN IF NOT EXISTS queue_ms INTEGER,
  ADD COLUMN IF NOT EXISTS retry_ms INTEGER;
