// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaiautoschedulerscorestate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIAutoSchedulerScoreStateUpdate is the builder for updating OpenAIAutoSchedulerScoreState entities.
type OpenAIAutoSchedulerScoreStateUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIAutoSchedulerScoreStateMutation
}

// Where appends a list predicates to the OpenAIAutoSchedulerScoreStateUpdate builder.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) Where(ps ...predicate.OpenAIAutoSchedulerScoreState) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetUpdatedAt(v time.Time) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetAccountID(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableAccountID(v *int64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddAccountID(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetGroupID(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableGroupID(v *int64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddGroupID(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetModel(v string) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableModel(v *string) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetFinalScore sets the "final_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetFinalScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetFinalScore()
	_u.mutation.SetFinalScore(v)
	return _u
}

// SetNillableFinalScore sets the "final_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableFinalScore(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetFinalScore(*v)
	}
	return _u
}

// AddFinalScore adds value to the "final_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddFinalScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddFinalScore(v)
	return _u
}

// SetBaseScore sets the "base_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetBaseScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetBaseScore()
	_u.mutation.SetBaseScore(v)
	return _u
}

// SetNillableBaseScore sets the "base_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableBaseScore(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetBaseScore(*v)
	}
	return _u
}

// AddBaseScore adds value to the "base_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddBaseScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddBaseScore(v)
	return _u
}

// SetLatencyScore sets the "latency_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetLatencyScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetLatencyScore()
	_u.mutation.SetLatencyScore(v)
	return _u
}

// SetNillableLatencyScore sets the "latency_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableLatencyScore(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetLatencyScore(*v)
	}
	return _u
}

// AddLatencyScore adds value to the "latency_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddLatencyScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddLatencyScore(v)
	return _u
}

// SetErrorScore sets the "error_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetErrorScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetErrorScore()
	_u.mutation.SetErrorScore(v)
	return _u
}

// SetNillableErrorScore sets the "error_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableErrorScore(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetErrorScore(*v)
	}
	return _u
}

// AddErrorScore adds value to the "error_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddErrorScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddErrorScore(v)
	return _u
}

// SetRecoveryScore sets the "recovery_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetRecoveryScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetRecoveryScore()
	_u.mutation.SetRecoveryScore(v)
	return _u
}

// SetNillableRecoveryScore sets the "recovery_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableRecoveryScore(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetRecoveryScore(*v)
	}
	return _u
}

// AddRecoveryScore adds value to the "recovery_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddRecoveryScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddRecoveryScore(v)
	return _u
}

// SetCostScore sets the "cost_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetCostScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetCostScore()
	_u.mutation.SetCostScore(v)
	return _u
}

// SetNillableCostScore sets the "cost_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableCostScore(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetCostScore(*v)
	}
	return _u
}

// AddCostScore adds value to the "cost_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddCostScore(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddCostScore(v)
	return _u
}

// SetState sets the "state" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetState(v string) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableState(v *string) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetConsecutiveSlowCount sets the "consecutive_slow_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetConsecutiveSlowCount(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetConsecutiveSlowCount()
	_u.mutation.SetConsecutiveSlowCount(v)
	return _u
}

// SetNillableConsecutiveSlowCount sets the "consecutive_slow_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableConsecutiveSlowCount(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetConsecutiveSlowCount(*v)
	}
	return _u
}

// AddConsecutiveSlowCount adds value to the "consecutive_slow_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddConsecutiveSlowCount(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddConsecutiveSlowCount(v)
	return _u
}

// SetConsecutiveErrorCount sets the "consecutive_error_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetConsecutiveErrorCount(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetConsecutiveErrorCount()
	_u.mutation.SetConsecutiveErrorCount(v)
	return _u
}

// SetNillableConsecutiveErrorCount sets the "consecutive_error_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableConsecutiveErrorCount(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetConsecutiveErrorCount(*v)
	}
	return _u
}

// AddConsecutiveErrorCount adds value to the "consecutive_error_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddConsecutiveErrorCount(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddConsecutiveErrorCount(v)
	return _u
}

// SetConsecutiveSuccessCount sets the "consecutive_success_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetConsecutiveSuccessCount(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetConsecutiveSuccessCount()
	_u.mutation.SetConsecutiveSuccessCount(v)
	return _u
}

// SetNillableConsecutiveSuccessCount sets the "consecutive_success_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableConsecutiveSuccessCount(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetConsecutiveSuccessCount(*v)
	}
	return _u
}

// AddConsecutiveSuccessCount adds value to the "consecutive_success_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddConsecutiveSuccessCount(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddConsecutiveSuccessCount(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetRequestCount(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableRequestCount(v *int64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddRequestCount(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetTtfbSampleCount sets the "ttfb_sample_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetTtfbSampleCount(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetTtfbSampleCount()
	_u.mutation.SetTtfbSampleCount(v)
	return _u
}

// SetNillableTtfbSampleCount sets the "ttfb_sample_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableTtfbSampleCount(v *int64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetTtfbSampleCount(*v)
	}
	return _u
}

// AddTtfbSampleCount adds value to the "ttfb_sample_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddTtfbSampleCount(v int64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddTtfbSampleCount(v)
	return _u
}

// SetSlowRate sets the "slow_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetSlowRate(v float64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetSlowRate()
	_u.mutation.SetSlowRate(v)
	return _u
}

// SetNillableSlowRate sets the "slow_rate" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableSlowRate(v *float64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetSlowRate(*v)
	}
	return _u
}

// AddSlowRate adds value to the "slow_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddSlowRate(v float64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddSlowRate(v)
	return _u
}

// SetErrorRate sets the "error_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetErrorRate(v float64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetErrorRate()
	_u.mutation.SetErrorRate(v)
	return _u
}

// SetNillableErrorRate sets the "error_rate" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableErrorRate(v *float64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetErrorRate(*v)
	}
	return _u
}

// AddErrorRate adds value to the "error_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddErrorRate(v float64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddErrorRate(v)
	return _u
}

// SetStuckRate sets the "stuck_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetStuckRate(v float64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetStuckRate()
	_u.mutation.SetStuckRate(v)
	return _u
}

// SetNillableStuckRate sets the "stuck_rate" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableStuckRate(v *float64) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetStuckRate(*v)
	}
	return _u
}

// AddStuckRate adds value to the "stuck_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddStuckRate(v float64) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddStuckRate(v)
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetCooldownUntil(v time.Time) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableCooldownUntil(v *time.Time) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ClearCooldownUntil() *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetLastLatencyMs sets the "last_latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetLastLatencyMs(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetLastLatencyMs()
	_u.mutation.SetLastLatencyMs(v)
	return _u
}

// SetNillableLastLatencyMs sets the "last_latency_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableLastLatencyMs(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetLastLatencyMs(*v)
	}
	return _u
}

// AddLastLatencyMs adds value to the "last_latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddLastLatencyMs(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddLastLatencyMs(v)
	return _u
}

// ClearLastLatencyMs clears the value of the "last_latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ClearLastLatencyMs() *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ClearLastLatencyMs()
	return _u
}

// SetLastTtfbMs sets the "last_ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetLastTtfbMs(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetLastTtfbMs()
	_u.mutation.SetLastTtfbMs(v)
	return _u
}

// SetNillableLastTtfbMs sets the "last_ttfb_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableLastTtfbMs(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetLastTtfbMs(*v)
	}
	return _u
}

// AddLastTtfbMs adds value to the "last_ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddLastTtfbMs(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddLastTtfbMs(v)
	return _u
}

// ClearLastTtfbMs clears the value of the "last_ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ClearLastTtfbMs() *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ClearLastTtfbMs()
	return _u
}

// SetLastStatusCode sets the "last_status_code" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetLastStatusCode(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ResetLastStatusCode()
	_u.mutation.SetLastStatusCode(v)
	return _u
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableLastStatusCode(v *int) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetLastStatusCode(*v)
	}
	return _u
}

// AddLastStatusCode adds value to the "last_status_code" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) AddLastStatusCode(v int) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.AddLastStatusCode(v)
	return _u
}

// ClearLastStatusCode clears the value of the "last_status_code" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ClearLastStatusCode() *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ClearLastStatusCode()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetLastError(v string) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableLastError(v *string) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ClearLastError() *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetReason sets the "reason" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetReason(v string) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableReason(v *string) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetLastCheckedAt(v time.Time) *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SetNillableLastCheckedAt(v *time.Time) *OpenAIAutoSchedulerScoreStateUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ClearLastCheckedAt() *OpenAIAutoSchedulerScoreStateUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// Mutation returns the OpenAIAutoSchedulerScoreStateMutation object of the builder.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) Mutation() *OpenAIAutoSchedulerScoreStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaiautoschedulerscorestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIAutoSchedulerScoreStateUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := openaiautoschedulerscorestate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreState.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := openaiautoschedulerscorestate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreState.state": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIAutoSchedulerScoreStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaiautoschedulerscorestate.Table, openaiautoschedulerscorestate.Columns, sqlgraph.NewFieldSpec(openaiautoschedulerscorestate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinalScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldFinalScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinalScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldFinalScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BaseScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldBaseScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBaseScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldBaseScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLatencyScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLatencyScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldErrorScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldErrorScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecoveryScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldRecoveryScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecoveryScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldRecoveryScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldCostScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldCostScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveSlowCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldConsecutiveSlowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveSlowCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldConsecutiveSlowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveErrorCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldConsecutiveErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveErrorCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldConsecutiveErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveSuccessCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldConsecutiveSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveSuccessCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldConsecutiveSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtfbSampleCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldTtfbSampleCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtfbSampleCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldTtfbSampleCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SlowRate(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldSlowRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSlowRate(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldSlowRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorRate(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldErrorRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedErrorRate(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldErrorRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StuckRate(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldStuckRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStuckRate(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldStuckRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastLatencyMs(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastLatencyMs(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLastLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LastLatencyMsCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastTtfbMs(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastTtfbMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastTtfbMs(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLastTtfbMs, field.TypeInt, value)
	}
	if _u.mutation.LastTtfbMsCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastTtfbMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastStatusCode(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastStatusCode(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLastStatusCode, field.TypeInt, value)
	}
	if _u.mutation.LastStatusCodeCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastCheckedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiautoschedulerscorestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIAutoSchedulerScoreStateUpdateOne is the builder for updating a single OpenAIAutoSchedulerScoreState entity.
type OpenAIAutoSchedulerScoreStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIAutoSchedulerScoreStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetUpdatedAt(v time.Time) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetAccountID(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableAccountID(v *int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddAccountID(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetGroupID(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableGroupID(v *int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddGroupID(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetModel(v string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableModel(v *string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetFinalScore sets the "final_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetFinalScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetFinalScore()
	_u.mutation.SetFinalScore(v)
	return _u
}

// SetNillableFinalScore sets the "final_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableFinalScore(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetFinalScore(*v)
	}
	return _u
}

// AddFinalScore adds value to the "final_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddFinalScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddFinalScore(v)
	return _u
}

// SetBaseScore sets the "base_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetBaseScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetBaseScore()
	_u.mutation.SetBaseScore(v)
	return _u
}

// SetNillableBaseScore sets the "base_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableBaseScore(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetBaseScore(*v)
	}
	return _u
}

// AddBaseScore adds value to the "base_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddBaseScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddBaseScore(v)
	return _u
}

// SetLatencyScore sets the "latency_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetLatencyScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetLatencyScore()
	_u.mutation.SetLatencyScore(v)
	return _u
}

// SetNillableLatencyScore sets the "latency_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableLatencyScore(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetLatencyScore(*v)
	}
	return _u
}

// AddLatencyScore adds value to the "latency_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddLatencyScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddLatencyScore(v)
	return _u
}

// SetErrorScore sets the "error_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetErrorScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetErrorScore()
	_u.mutation.SetErrorScore(v)
	return _u
}

// SetNillableErrorScore sets the "error_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableErrorScore(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetErrorScore(*v)
	}
	return _u
}

// AddErrorScore adds value to the "error_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddErrorScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddErrorScore(v)
	return _u
}

// SetRecoveryScore sets the "recovery_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetRecoveryScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetRecoveryScore()
	_u.mutation.SetRecoveryScore(v)
	return _u
}

// SetNillableRecoveryScore sets the "recovery_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableRecoveryScore(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetRecoveryScore(*v)
	}
	return _u
}

// AddRecoveryScore adds value to the "recovery_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddRecoveryScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddRecoveryScore(v)
	return _u
}

// SetCostScore sets the "cost_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetCostScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetCostScore()
	_u.mutation.SetCostScore(v)
	return _u
}

// SetNillableCostScore sets the "cost_score" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableCostScore(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetCostScore(*v)
	}
	return _u
}

// AddCostScore adds value to the "cost_score" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddCostScore(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddCostScore(v)
	return _u
}

// SetState sets the "state" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetState(v string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableState(v *string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetConsecutiveSlowCount sets the "consecutive_slow_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetConsecutiveSlowCount(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetConsecutiveSlowCount()
	_u.mutation.SetConsecutiveSlowCount(v)
	return _u
}

// SetNillableConsecutiveSlowCount sets the "consecutive_slow_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableConsecutiveSlowCount(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetConsecutiveSlowCount(*v)
	}
	return _u
}

// AddConsecutiveSlowCount adds value to the "consecutive_slow_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddConsecutiveSlowCount(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddConsecutiveSlowCount(v)
	return _u
}

// SetConsecutiveErrorCount sets the "consecutive_error_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetConsecutiveErrorCount(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetConsecutiveErrorCount()
	_u.mutation.SetConsecutiveErrorCount(v)
	return _u
}

// SetNillableConsecutiveErrorCount sets the "consecutive_error_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableConsecutiveErrorCount(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetConsecutiveErrorCount(*v)
	}
	return _u
}

// AddConsecutiveErrorCount adds value to the "consecutive_error_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddConsecutiveErrorCount(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddConsecutiveErrorCount(v)
	return _u
}

// SetConsecutiveSuccessCount sets the "consecutive_success_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetConsecutiveSuccessCount(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetConsecutiveSuccessCount()
	_u.mutation.SetConsecutiveSuccessCount(v)
	return _u
}

// SetNillableConsecutiveSuccessCount sets the "consecutive_success_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableConsecutiveSuccessCount(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetConsecutiveSuccessCount(*v)
	}
	return _u
}

// AddConsecutiveSuccessCount adds value to the "consecutive_success_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddConsecutiveSuccessCount(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddConsecutiveSuccessCount(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetRequestCount(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableRequestCount(v *int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddRequestCount(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetTtfbSampleCount sets the "ttfb_sample_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetTtfbSampleCount(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetTtfbSampleCount()
	_u.mutation.SetTtfbSampleCount(v)
	return _u
}

// SetNillableTtfbSampleCount sets the "ttfb_sample_count" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableTtfbSampleCount(v *int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetTtfbSampleCount(*v)
	}
	return _u
}

// AddTtfbSampleCount adds value to the "ttfb_sample_count" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddTtfbSampleCount(v int64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddTtfbSampleCount(v)
	return _u
}

// SetSlowRate sets the "slow_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetSlowRate(v float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetSlowRate()
	_u.mutation.SetSlowRate(v)
	return _u
}

// SetNillableSlowRate sets the "slow_rate" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableSlowRate(v *float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetSlowRate(*v)
	}
	return _u
}

// AddSlowRate adds value to the "slow_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddSlowRate(v float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddSlowRate(v)
	return _u
}

// SetErrorRate sets the "error_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetErrorRate(v float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetErrorRate()
	_u.mutation.SetErrorRate(v)
	return _u
}

// SetNillableErrorRate sets the "error_rate" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableErrorRate(v *float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetErrorRate(*v)
	}
	return _u
}

// AddErrorRate adds value to the "error_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddErrorRate(v float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddErrorRate(v)
	return _u
}

// SetStuckRate sets the "stuck_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetStuckRate(v float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetStuckRate()
	_u.mutation.SetStuckRate(v)
	return _u
}

// SetNillableStuckRate sets the "stuck_rate" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableStuckRate(v *float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetStuckRate(*v)
	}
	return _u
}

// AddStuckRate adds value to the "stuck_rate" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddStuckRate(v float64) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddStuckRate(v)
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetCooldownUntil(v time.Time) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableCooldownUntil(v *time.Time) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ClearCooldownUntil() *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetLastLatencyMs sets the "last_latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetLastLatencyMs(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetLastLatencyMs()
	_u.mutation.SetLastLatencyMs(v)
	return _u
}

// SetNillableLastLatencyMs sets the "last_latency_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableLastLatencyMs(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetLastLatencyMs(*v)
	}
	return _u
}

// AddLastLatencyMs adds value to the "last_latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddLastLatencyMs(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddLastLatencyMs(v)
	return _u
}

// ClearLastLatencyMs clears the value of the "last_latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ClearLastLatencyMs() *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ClearLastLatencyMs()
	return _u
}

// SetLastTtfbMs sets the "last_ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetLastTtfbMs(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetLastTtfbMs()
	_u.mutation.SetLastTtfbMs(v)
	return _u
}

// SetNillableLastTtfbMs sets the "last_ttfb_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableLastTtfbMs(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetLastTtfbMs(*v)
	}
	return _u
}

// AddLastTtfbMs adds value to the "last_ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddLastTtfbMs(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddLastTtfbMs(v)
	return _u
}

// ClearLastTtfbMs clears the value of the "last_ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ClearLastTtfbMs() *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ClearLastTtfbMs()
	return _u
}

// SetLastStatusCode sets the "last_status_code" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetLastStatusCode(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ResetLastStatusCode()
	_u.mutation.SetLastStatusCode(v)
	return _u
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableLastStatusCode(v *int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetLastStatusCode(*v)
	}
	return _u
}

// AddLastStatusCode adds value to the "last_status_code" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) AddLastStatusCode(v int) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.AddLastStatusCode(v)
	return _u
}

// ClearLastStatusCode clears the value of the "last_status_code" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ClearLastStatusCode() *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ClearLastStatusCode()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetLastError(v string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableLastError(v *string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ClearLastError() *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetReason sets the "reason" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetReason(v string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableReason(v *string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetLastCheckedAt(v time.Time) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SetNillableLastCheckedAt(v *time.Time) *OpenAIAutoSchedulerScoreStateUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ClearLastCheckedAt() *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// Mutation returns the OpenAIAutoSchedulerScoreStateMutation object of the builder.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) Mutation() *OpenAIAutoSchedulerScoreStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIAutoSchedulerScoreStateUpdate builder.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) Where(ps ...predicate.OpenAIAutoSchedulerScoreState) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) Select(field string, fields ...string) *OpenAIAutoSchedulerScoreStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIAutoSchedulerScoreState entity.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) Save(ctx context.Context) (*OpenAIAutoSchedulerScoreState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) SaveX(ctx context.Context) *OpenAIAutoSchedulerScoreState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaiautoschedulerscorestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := openaiautoschedulerscorestate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreState.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := openaiautoschedulerscorestate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreState.state": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIAutoSchedulerScoreStateUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIAutoSchedulerScoreState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaiautoschedulerscorestate.Table, openaiautoschedulerscorestate.Columns, sqlgraph.NewFieldSpec(openaiautoschedulerscorestate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIAutoSchedulerScoreState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaiautoschedulerscorestate.FieldID)
		for _, f := range fields {
			if !openaiautoschedulerscorestate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaiautoschedulerscorestate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinalScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldFinalScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinalScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldFinalScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BaseScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldBaseScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBaseScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldBaseScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLatencyScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLatencyScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldErrorScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldErrorScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecoveryScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldRecoveryScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecoveryScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldRecoveryScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostScore(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldCostScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostScore(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldCostScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveSlowCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldConsecutiveSlowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveSlowCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldConsecutiveSlowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveErrorCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldConsecutiveErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveErrorCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldConsecutiveErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsecutiveSuccessCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldConsecutiveSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveSuccessCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldConsecutiveSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtfbSampleCount(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldTtfbSampleCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtfbSampleCount(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldTtfbSampleCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SlowRate(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldSlowRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSlowRate(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldSlowRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorRate(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldErrorRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedErrorRate(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldErrorRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StuckRate(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldStuckRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStuckRate(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldStuckRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastLatencyMs(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastLatencyMs(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLastLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LastLatencyMsCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastTtfbMs(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastTtfbMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastTtfbMs(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLastTtfbMs, field.TypeInt, value)
	}
	if _u.mutation.LastTtfbMsCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastTtfbMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastStatusCode(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastStatusCode(); ok {
		_spec.AddField(openaiautoschedulerscorestate.FieldLastStatusCode, field.TypeInt, value)
	}
	if _u.mutation.LastStatusCodeCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(openaiautoschedulerscorestate.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(openaiautoschedulerscorestate.FieldLastCheckedAt, field.TypeTime)
	}
	_node = &OpenAIAutoSchedulerScoreState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiautoschedulerscorestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
