// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaiautoschedulerscoreevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIAutoSchedulerScoreEventUpdate is the builder for updating OpenAIAutoSchedulerScoreEvent entities.
type OpenAIAutoSchedulerScoreEventUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIAutoSchedulerScoreEventMutation
}

// Where appends a list predicates to the OpenAIAutoSchedulerScoreEventUpdate builder.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) Where(ps ...predicate.OpenAIAutoSchedulerScoreEvent) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetAccountID(v int64) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableAccountID(v *int64) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddAccountID(v int64) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetGroupID(v int64) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableGroupID(v *int64) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddGroupID(v int64) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetModel(v string) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableModel(v *string) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetEventType(v string) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableEventType(v *string) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetScoreBefore sets the "score_before" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetScoreBefore(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetScoreBefore()
	_u.mutation.SetScoreBefore(v)
	return _u
}

// SetNillableScoreBefore sets the "score_before" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableScoreBefore(v *int) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetScoreBefore(*v)
	}
	return _u
}

// AddScoreBefore adds value to the "score_before" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddScoreBefore(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddScoreBefore(v)
	return _u
}

// SetScoreAfter sets the "score_after" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetScoreAfter(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetScoreAfter()
	_u.mutation.SetScoreAfter(v)
	return _u
}

// SetNillableScoreAfter sets the "score_after" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableScoreAfter(v *int) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetScoreAfter(*v)
	}
	return _u
}

// AddScoreAfter adds value to the "score_after" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddScoreAfter(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddScoreAfter(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetLatencyMs(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableLatencyMs(v *int) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddLatencyMs(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) ClearLatencyMs() *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetTtfbMs(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetTtfbMs()
	_u.mutation.SetTtfbMs(v)
	return _u
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableTtfbMs(v *int) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetTtfbMs(*v)
	}
	return _u
}

// AddTtfbMs adds value to the "ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddTtfbMs(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddTtfbMs(v)
	return _u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) ClearTtfbMs() *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ClearTtfbMs()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetStatusCode(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableStatusCode(v *int) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) AddStatusCode(v int) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) ClearStatusCode() *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetMessage sets the "message" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetMessage(v string) *OpenAIAutoSchedulerScoreEventUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SetNillableMessage(v *string) *OpenAIAutoSchedulerScoreEventUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// Mutation returns the OpenAIAutoSchedulerScoreEventMutation object of the builder.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) Mutation() *OpenAIAutoSchedulerScoreEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIAutoSchedulerScoreEventUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := openaiautoschedulerscoreevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := openaiautoschedulerscoreevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScoreBefore(); ok {
		if err := openaiautoschedulerscoreevent.ScoreBeforeValidator(v); err != nil {
			return &ValidationError{Name: "score_before", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.score_before": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScoreAfter(); ok {
		if err := openaiautoschedulerscoreevent.ScoreAfterValidator(v); err != nil {
			return &ValidationError{Name: "score_after", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.score_after": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIAutoSchedulerScoreEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaiautoschedulerscoreevent.Table, openaiautoschedulerscoreevent.Columns, sqlgraph.NewFieldSpec(openaiautoschedulerscoreevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScoreBefore(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldScoreBefore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScoreBefore(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldScoreBefore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScoreAfter(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldScoreAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScoreAfter(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldScoreAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(openaiautoschedulerscoreevent.FieldLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.TtfbMs(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldTtfbMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTtfbMs(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldTtfbMs, field.TypeInt, value)
	}
	if _u.mutation.TtfbMsCleared() {
		_spec.ClearField(openaiautoschedulerscoreevent.FieldTtfbMs, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(openaiautoschedulerscoreevent.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldMessage, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiautoschedulerscoreevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIAutoSchedulerScoreEventUpdateOne is the builder for updating a single OpenAIAutoSchedulerScoreEvent entity.
type OpenAIAutoSchedulerScoreEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIAutoSchedulerScoreEventMutation
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetAccountID(v int64) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableAccountID(v *int64) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddAccountID(v int64) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetGroupID(v int64) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableGroupID(v *int64) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddGroupID(v int64) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetModel(v string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableModel(v *string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetEventType(v string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableEventType(v *string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetScoreBefore sets the "score_before" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetScoreBefore(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetScoreBefore()
	_u.mutation.SetScoreBefore(v)
	return _u
}

// SetNillableScoreBefore sets the "score_before" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableScoreBefore(v *int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetScoreBefore(*v)
	}
	return _u
}

// AddScoreBefore adds value to the "score_before" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddScoreBefore(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddScoreBefore(v)
	return _u
}

// SetScoreAfter sets the "score_after" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetScoreAfter(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetScoreAfter()
	_u.mutation.SetScoreAfter(v)
	return _u
}

// SetNillableScoreAfter sets the "score_after" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableScoreAfter(v *int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetScoreAfter(*v)
	}
	return _u
}

// AddScoreAfter adds value to the "score_after" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddScoreAfter(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddScoreAfter(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetLatencyMs(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableLatencyMs(v *int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddLatencyMs(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) ClearLatencyMs() *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetTtfbMs(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetTtfbMs()
	_u.mutation.SetTtfbMs(v)
	return _u
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableTtfbMs(v *int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetTtfbMs(*v)
	}
	return _u
}

// AddTtfbMs adds value to the "ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddTtfbMs(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddTtfbMs(v)
	return _u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) ClearTtfbMs() *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ClearTtfbMs()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetStatusCode(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableStatusCode(v *int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) AddStatusCode(v int) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) ClearStatusCode() *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetMessage sets the "message" field.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetMessage(v string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SetNillableMessage(v *string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// Mutation returns the OpenAIAutoSchedulerScoreEventMutation object of the builder.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) Mutation() *OpenAIAutoSchedulerScoreEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIAutoSchedulerScoreEventUpdate builder.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) Where(ps ...predicate.OpenAIAutoSchedulerScoreEvent) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) Select(field string, fields ...string) *OpenAIAutoSchedulerScoreEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIAutoSchedulerScoreEvent entity.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) Save(ctx context.Context) (*OpenAIAutoSchedulerScoreEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) SaveX(ctx context.Context) *OpenAIAutoSchedulerScoreEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := openaiautoschedulerscoreevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := openaiautoschedulerscoreevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScoreBefore(); ok {
		if err := openaiautoschedulerscoreevent.ScoreBeforeValidator(v); err != nil {
			return &ValidationError{Name: "score_before", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.score_before": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScoreAfter(); ok {
		if err := openaiautoschedulerscoreevent.ScoreAfterValidator(v); err != nil {
			return &ValidationError{Name: "score_after", err: fmt.Errorf(`ent: validator failed for field "OpenAIAutoSchedulerScoreEvent.score_after": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIAutoSchedulerScoreEventUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIAutoSchedulerScoreEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaiautoschedulerscoreevent.Table, openaiautoschedulerscoreevent.Columns, sqlgraph.NewFieldSpec(openaiautoschedulerscoreevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIAutoSchedulerScoreEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaiautoschedulerscoreevent.FieldID)
		for _, f := range fields {
			if !openaiautoschedulerscoreevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaiautoschedulerscoreevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScoreBefore(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldScoreBefore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScoreBefore(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldScoreBefore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScoreAfter(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldScoreAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScoreAfter(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldScoreAfter, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(openaiautoschedulerscoreevent.FieldLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.TtfbMs(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldTtfbMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTtfbMs(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldTtfbMs, field.TypeInt, value)
	}
	if _u.mutation.TtfbMsCleared() {
		_spec.ClearField(openaiautoschedulerscoreevent.FieldTtfbMs, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(openaiautoschedulerscoreevent.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(openaiautoschedulerscoreevent.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(openaiautoschedulerscoreevent.FieldMessage, field.TypeString, value)
	}
	_node = &OpenAIAutoSchedulerScoreEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiautoschedulerscoreevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
