// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaiautoschedulerscorestate"
)

// OpenAIAutoSchedulerScoreState is the model entity for the OpenAIAutoSchedulerScoreState schema.
type OpenAIAutoSchedulerScoreState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// FinalScore holds the value of the "final_score" field.
	FinalScore int `json:"final_score,omitempty"`
	// BaseScore holds the value of the "base_score" field.
	BaseScore int `json:"base_score,omitempty"`
	// LatencyScore holds the value of the "latency_score" field.
	LatencyScore int `json:"latency_score,omitempty"`
	// ErrorScore holds the value of the "error_score" field.
	ErrorScore int `json:"error_score,omitempty"`
	// RecoveryScore holds the value of the "recovery_score" field.
	RecoveryScore int `json:"recovery_score,omitempty"`
	// CostScore holds the value of the "cost_score" field.
	CostScore int `json:"cost_score,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ConsecutiveSlowCount holds the value of the "consecutive_slow_count" field.
	ConsecutiveSlowCount int `json:"consecutive_slow_count,omitempty"`
	// ConsecutiveErrorCount holds the value of the "consecutive_error_count" field.
	ConsecutiveErrorCount int `json:"consecutive_error_count,omitempty"`
	// ConsecutiveSuccessCount holds the value of the "consecutive_success_count" field.
	ConsecutiveSuccessCount int `json:"consecutive_success_count,omitempty"`
	// RequestCount holds the value of the "request_count" field.
	RequestCount int64 `json:"request_count,omitempty"`
	// TtfbSampleCount holds the value of the "ttfb_sample_count" field.
	TtfbSampleCount int64 `json:"ttfb_sample_count,omitempty"`
	// SlowRate holds the value of the "slow_rate" field.
	SlowRate float64 `json:"slow_rate,omitempty"`
	// ErrorRate holds the value of the "error_rate" field.
	ErrorRate float64 `json:"error_rate,omitempty"`
	// StuckRate holds the value of the "stuck_rate" field.
	StuckRate float64 `json:"stuck_rate,omitempty"`
	// CooldownUntil holds the value of the "cooldown_until" field.
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// LastLatencyMs holds the value of the "last_latency_ms" field.
	LastLatencyMs *int `json:"last_latency_ms,omitempty"`
	// LastTtfbMs holds the value of the "last_ttfb_ms" field.
	LastTtfbMs *int `json:"last_ttfb_ms,omitempty"`
	// LastStatusCode holds the value of the "last_status_code" field.
	LastStatusCode *int `json:"last_status_code,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIAutoSchedulerScoreState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaiautoschedulerscorestate.FieldSlowRate, openaiautoschedulerscorestate.FieldErrorRate, openaiautoschedulerscorestate.FieldStuckRate:
			values[i] = new(sql.NullFloat64)
		case openaiautoschedulerscorestate.FieldID, openaiautoschedulerscorestate.FieldAccountID, openaiautoschedulerscorestate.FieldGroupID, openaiautoschedulerscorestate.FieldFinalScore, openaiautoschedulerscorestate.FieldBaseScore, openaiautoschedulerscorestate.FieldLatencyScore, openaiautoschedulerscorestate.FieldErrorScore, openaiautoschedulerscorestate.FieldRecoveryScore, openaiautoschedulerscorestate.FieldCostScore, openaiautoschedulerscorestate.FieldConsecutiveSlowCount, openaiautoschedulerscorestate.FieldConsecutiveErrorCount, openaiautoschedulerscorestate.FieldConsecutiveSuccessCount, openaiautoschedulerscorestate.FieldRequestCount, openaiautoschedulerscorestate.FieldTtfbSampleCount, openaiautoschedulerscorestate.FieldLastLatencyMs, openaiautoschedulerscorestate.FieldLastTtfbMs, openaiautoschedulerscorestate.FieldLastStatusCode:
			values[i] = new(sql.NullInt64)
		case openaiautoschedulerscorestate.FieldModel, openaiautoschedulerscorestate.FieldState, openaiautoschedulerscorestate.FieldLastError, openaiautoschedulerscorestate.FieldReason:
			values[i] = new(sql.NullString)
		case openaiautoschedulerscorestate.FieldCreatedAt, openaiautoschedulerscorestate.FieldUpdatedAt, openaiautoschedulerscorestate.FieldCooldownUntil, openaiautoschedulerscorestate.FieldLastCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIAutoSchedulerScoreState fields.
func (_m *OpenAIAutoSchedulerScoreState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaiautoschedulerscorestate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaiautoschedulerscorestate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaiautoschedulerscorestate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case openaiautoschedulerscorestate.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaiautoschedulerscorestate.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case openaiautoschedulerscorestate.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case openaiautoschedulerscorestate.FieldFinalScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field final_score", values[i])
			} else if value.Valid {
				_m.FinalScore = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldBaseScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field base_score", values[i])
			} else if value.Valid {
				_m.BaseScore = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldLatencyScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_score", values[i])
			} else if value.Valid {
				_m.LatencyScore = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldErrorScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_score", values[i])
			} else if value.Valid {
				_m.ErrorScore = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldRecoveryScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_score", values[i])
			} else if value.Valid {
				_m.RecoveryScore = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldCostScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_score", values[i])
			} else if value.Valid {
				_m.CostScore = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case openaiautoschedulerscorestate.FieldConsecutiveSlowCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_slow_count", values[i])
			} else if value.Valid {
				_m.ConsecutiveSlowCount = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldConsecutiveErrorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_error_count", values[i])
			} else if value.Valid {
				_m.ConsecutiveErrorCount = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldConsecutiveSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_success_count", values[i])
			} else if value.Valid {
				_m.ConsecutiveSuccessCount = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_count", values[i])
			} else if value.Valid {
				_m.RequestCount = value.Int64
			}
		case openaiautoschedulerscorestate.FieldTtfbSampleCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ttfb_sample_count", values[i])
			} else if value.Valid {
				_m.TtfbSampleCount = value.Int64
			}
		case openaiautoschedulerscorestate.FieldSlowRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field slow_rate", values[i])
			} else if value.Valid {
				_m.SlowRate = value.Float64
			}
		case openaiautoschedulerscorestate.FieldErrorRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field error_rate", values[i])
			} else if value.Valid {
				_m.ErrorRate = value.Float64
			}
		case openaiautoschedulerscorestate.FieldStuckRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field stuck_rate", values[i])
			} else if value.Valid {
				_m.StuckRate = value.Float64
			}
		case openaiautoschedulerscorestate.FieldCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_until", values[i])
			} else if value.Valid {
				_m.CooldownUntil = new(time.Time)
				*_m.CooldownUntil = value.Time
			}
		case openaiautoschedulerscorestate.FieldLastLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_latency_ms", values[i])
			} else if value.Valid {
				_m.LastLatencyMs = new(int)
				*_m.LastLatencyMs = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldLastTtfbMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_ttfb_ms", values[i])
			} else if value.Valid {
				_m.LastTtfbMs = new(int)
				*_m.LastTtfbMs = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldLastStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_status_code", values[i])
			} else if value.Valid {
				_m.LastStatusCode = new(int)
				*_m.LastStatusCode = int(value.Int64)
			}
		case openaiautoschedulerscorestate.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case openaiautoschedulerscorestate.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case openaiautoschedulerscorestate.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIAutoSchedulerScoreState.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIAutoSchedulerScoreState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIAutoSchedulerScoreState.
// Note that you need to call OpenAIAutoSchedulerScoreState.Unwrap() before calling this method if this OpenAIAutoSchedulerScoreState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIAutoSchedulerScoreState) Update() *OpenAIAutoSchedulerScoreStateUpdateOne {
	return NewOpenAIAutoSchedulerScoreStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIAutoSchedulerScoreState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIAutoSchedulerScoreState) Unwrap() *OpenAIAutoSchedulerScoreState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIAutoSchedulerScoreState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIAutoSchedulerScoreState) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIAutoSchedulerScoreState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("final_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinalScore))
	builder.WriteString(", ")
	builder.WriteString("base_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseScore))
	builder.WriteString(", ")
	builder.WriteString("latency_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyScore))
	builder.WriteString(", ")
	builder.WriteString("error_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorScore))
	builder.WriteString(", ")
	builder.WriteString("recovery_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoveryScore))
	builder.WriteString(", ")
	builder.WriteString("cost_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostScore))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("consecutive_slow_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveSlowCount))
	builder.WriteString(", ")
	builder.WriteString("consecutive_error_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveErrorCount))
	builder.WriteString(", ")
	builder.WriteString("consecutive_success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveSuccessCount))
	builder.WriteString(", ")
	builder.WriteString("request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestCount))
	builder.WriteString(", ")
	builder.WriteString("ttfb_sample_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TtfbSampleCount))
	builder.WriteString(", ")
	builder.WriteString("slow_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.SlowRate))
	builder.WriteString(", ")
	builder.WriteString("error_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorRate))
	builder.WriteString(", ")
	builder.WriteString("stuck_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.StuckRate))
	builder.WriteString(", ")
	if v := _m.CooldownUntil; v != nil {
		builder.WriteString("cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastLatencyMs; v != nil {
		builder.WriteString("last_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastTtfbMs; v != nil {
		builder.WriteString("last_ttfb_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastStatusCode; v != nil {
		builder.WriteString("last_status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIAutoSchedulerScoreStates is a parsable slice of OpenAIAutoSchedulerScoreState.
type OpenAIAutoSchedulerScoreStates []*OpenAIAutoSchedulerScoreState
