// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaischedulerhealthstate"
)

// OpenAISchedulerHealthState is the model entity for the OpenAISchedulerHealthState schema.
type OpenAISchedulerHealthState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ModelFamily holds the value of the "model_family" field.
	ModelFamily string `json:"model_family,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Transport holds the value of the "transport" field.
	Transport string `json:"transport,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// PredictedTtftMs holds the value of the "predicted_ttft_ms" field.
	PredictedTtftMs float64 `json:"predicted_ttft_ms,omitempty"`
	// ErrorRate holds the value of the "error_rate" field.
	ErrorRate float64 `json:"error_rate,omitempty"`
	// RateLimitedRate holds the value of the "rate_limited_rate" field.
	RateLimitedRate float64 `json:"rate_limited_rate,omitempty"`
	// ServerErrorRate holds the value of the "server_error_rate" field.
	ServerErrorRate float64 `json:"server_error_rate,omitempty"`
	// ConsecutiveSlow holds the value of the "consecutive_slow" field.
	ConsecutiveSlow int `json:"consecutive_slow,omitempty"`
	// ConsecutiveError holds the value of the "consecutive_error" field.
	ConsecutiveError int `json:"consecutive_error,omitempty"`
	// ConsecutiveSuccess holds the value of the "consecutive_success" field.
	ConsecutiveSuccess int `json:"consecutive_success,omitempty"`
	// RealSampleCount holds the value of the "real_sample_count" field.
	RealSampleCount int64 `json:"real_sample_count,omitempty"`
	// ProbeSampleCount holds the value of the "probe_sample_count" field.
	ProbeSampleCount int64 `json:"probe_sample_count,omitempty"`
	// LastRealAt holds the value of the "last_real_at" field.
	LastRealAt *time.Time `json:"last_real_at,omitempty"`
	// LastProbeAt holds the value of the "last_probe_at" field.
	LastProbeAt *time.Time `json:"last_probe_at,omitempty"`
	// CooldownUntil holds the value of the "cooldown_until" field.
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAISchedulerHealthState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaischedulerhealthstate.FieldPredictedTtftMs, openaischedulerhealthstate.FieldErrorRate, openaischedulerhealthstate.FieldRateLimitedRate, openaischedulerhealthstate.FieldServerErrorRate:
			values[i] = new(sql.NullFloat64)
		case openaischedulerhealthstate.FieldID, openaischedulerhealthstate.FieldAccountID, openaischedulerhealthstate.FieldConsecutiveSlow, openaischedulerhealthstate.FieldConsecutiveError, openaischedulerhealthstate.FieldConsecutiveSuccess, openaischedulerhealthstate.FieldRealSampleCount, openaischedulerhealthstate.FieldProbeSampleCount:
			values[i] = new(sql.NullInt64)
		case openaischedulerhealthstate.FieldModelFamily, openaischedulerhealthstate.FieldEndpoint, openaischedulerhealthstate.FieldTransport, openaischedulerhealthstate.FieldState:
			values[i] = new(sql.NullString)
		case openaischedulerhealthstate.FieldCreatedAt, openaischedulerhealthstate.FieldUpdatedAt, openaischedulerhealthstate.FieldLastRealAt, openaischedulerhealthstate.FieldLastProbeAt, openaischedulerhealthstate.FieldCooldownUntil, openaischedulerhealthstate.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAISchedulerHealthState fields.
func (_m *OpenAISchedulerHealthState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaischedulerhealthstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaischedulerhealthstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaischedulerhealthstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case openaischedulerhealthstate.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaischedulerhealthstate.FieldModelFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_family", values[i])
			} else if value.Valid {
				_m.ModelFamily = value.String
			}
		case openaischedulerhealthstate.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case openaischedulerhealthstate.FieldTransport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transport", values[i])
			} else if value.Valid {
				_m.Transport = value.String
			}
		case openaischedulerhealthstate.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case openaischedulerhealthstate.FieldPredictedTtftMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field predicted_ttft_ms", values[i])
			} else if value.Valid {
				_m.PredictedTtftMs = value.Float64
			}
		case openaischedulerhealthstate.FieldErrorRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field error_rate", values[i])
			} else if value.Valid {
				_m.ErrorRate = value.Float64
			}
		case openaischedulerhealthstate.FieldRateLimitedRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limited_rate", values[i])
			} else if value.Valid {
				_m.RateLimitedRate = value.Float64
			}
		case openaischedulerhealthstate.FieldServerErrorRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field server_error_rate", values[i])
			} else if value.Valid {
				_m.ServerErrorRate = value.Float64
			}
		case openaischedulerhealthstate.FieldConsecutiveSlow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_slow", values[i])
			} else if value.Valid {
				_m.ConsecutiveSlow = int(value.Int64)
			}
		case openaischedulerhealthstate.FieldConsecutiveError:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_error", values[i])
			} else if value.Valid {
				_m.ConsecutiveError = int(value.Int64)
			}
		case openaischedulerhealthstate.FieldConsecutiveSuccess:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_success", values[i])
			} else if value.Valid {
				_m.ConsecutiveSuccess = int(value.Int64)
			}
		case openaischedulerhealthstate.FieldRealSampleCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_sample_count", values[i])
			} else if value.Valid {
				_m.RealSampleCount = value.Int64
			}
		case openaischedulerhealthstate.FieldProbeSampleCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_sample_count", values[i])
			} else if value.Valid {
				_m.ProbeSampleCount = value.Int64
			}
		case openaischedulerhealthstate.FieldLastRealAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_real_at", values[i])
			} else if value.Valid {
				_m.LastRealAt = new(time.Time)
				*_m.LastRealAt = value.Time
			}
		case openaischedulerhealthstate.FieldLastProbeAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_at", values[i])
			} else if value.Valid {
				_m.LastProbeAt = new(time.Time)
				*_m.LastProbeAt = value.Time
			}
		case openaischedulerhealthstate.FieldCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_until", values[i])
			} else if value.Valid {
				_m.CooldownUntil = new(time.Time)
				*_m.CooldownUntil = value.Time
			}
		case openaischedulerhealthstate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAISchedulerHealthState.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAISchedulerHealthState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAISchedulerHealthState.
// Note that you need to call OpenAISchedulerHealthState.Unwrap() before calling this method if this OpenAISchedulerHealthState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAISchedulerHealthState) Update() *OpenAISchedulerHealthStateUpdateOne {
	return NewOpenAISchedulerHealthStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAISchedulerHealthState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAISchedulerHealthState) Unwrap() *OpenAISchedulerHealthState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAISchedulerHealthState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAISchedulerHealthState) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAISchedulerHealthState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("model_family=")
	builder.WriteString(_m.ModelFamily)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("transport=")
	builder.WriteString(_m.Transport)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("predicted_ttft_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.PredictedTtftMs))
	builder.WriteString(", ")
	builder.WriteString("error_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorRate))
	builder.WriteString(", ")
	builder.WriteString("rate_limited_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimitedRate))
	builder.WriteString(", ")
	builder.WriteString("server_error_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServerErrorRate))
	builder.WriteString(", ")
	builder.WriteString("consecutive_slow=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveSlow))
	builder.WriteString(", ")
	builder.WriteString("consecutive_error=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveError))
	builder.WriteString(", ")
	builder.WriteString("consecutive_success=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveSuccess))
	builder.WriteString(", ")
	builder.WriteString("real_sample_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealSampleCount))
	builder.WriteString(", ")
	builder.WriteString("probe_sample_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeSampleCount))
	builder.WriteString(", ")
	if v := _m.LastRealAt; v != nil {
		builder.WriteString("last_real_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastProbeAt; v != nil {
		builder.WriteString("last_probe_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CooldownUntil; v != nil {
		builder.WriteString("cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAISchedulerHealthStates is a parsable slice of OpenAISchedulerHealthState.
type OpenAISchedulerHealthStates []*OpenAISchedulerHealthState
