// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaiautoschedulerscoreevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIAutoSchedulerScoreEventDelete is the builder for deleting a OpenAIAutoSchedulerScoreEvent entity.
type OpenAIAutoSchedulerScoreEventDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIAutoSchedulerScoreEventMutation
}

// Where appends a list predicates to the OpenAIAutoSchedulerScoreEventDelete builder.
func (_d *OpenAIAutoSchedulerScoreEventDelete) Where(ps ...predicate.OpenAIAutoSchedulerScoreEvent) *OpenAIAutoSchedulerScoreEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIAutoSchedulerScoreEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIAutoSchedulerScoreEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIAutoSchedulerScoreEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaiautoschedulerscoreevent.Table, sqlgraph.NewFieldSpec(openaiautoschedulerscoreevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIAutoSchedulerScoreEventDeleteOne is the builder for deleting a single OpenAIAutoSchedulerScoreEvent entity.
type OpenAIAutoSchedulerScoreEventDeleteOne struct {
	_d *OpenAIAutoSchedulerScoreEventDelete
}

// Where appends a list predicates to the OpenAIAutoSchedulerScoreEventDelete builder.
func (_d *OpenAIAutoSchedulerScoreEventDeleteOne) Where(ps ...predicate.OpenAIAutoSchedulerScoreEvent) *OpenAIAutoSchedulerScoreEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIAutoSchedulerScoreEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaiautoschedulerscoreevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIAutoSchedulerScoreEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
