// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/windsurfaccount"
)

// WindsurfAccountUpdate is the builder for updating WindsurfAccount entities.
type WindsurfAccountUpdate struct {
	config
	hooks    []Hook
	mutation *WindsurfAccountMutation
}

// Where appends a list predicates to the WindsurfAccountUpdate builder.
func (_u *WindsurfAccountUpdate) Where(ps ...predicate.WindsurfAccount) *WindsurfAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WindsurfAccountUpdate) SetUpdatedAt(v time.Time) *WindsurfAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" field.
func (_u *WindsurfAccountUpdate) SetAccount(v string) *WindsurfAccountUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillableAccount(v *string) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *WindsurfAccountUpdate) SetPasswordEncrypted(v string) *WindsurfAccountUpdate {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillablePasswordEncrypted(v *string) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WindsurfAccountUpdate) SetEnabled(v bool) *WindsurfAccountUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillableEnabled(v *bool) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMaintainedBy sets the "maintained_by" field.
func (_u *WindsurfAccountUpdate) SetMaintainedBy(v int64) *WindsurfAccountUpdate {
	_u.mutation.ResetMaintainedBy()
	_u.mutation.SetMaintainedBy(v)
	return _u
}

// SetNillableMaintainedBy sets the "maintained_by" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillableMaintainedBy(v *int64) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetMaintainedBy(*v)
	}
	return _u
}

// AddMaintainedBy adds value to the "maintained_by" field.
func (_u *WindsurfAccountUpdate) AddMaintainedBy(v int64) *WindsurfAccountUpdate {
	_u.mutation.AddMaintainedBy(v)
	return _u
}

// SetMaintainedAt sets the "maintained_at" field.
func (_u *WindsurfAccountUpdate) SetMaintainedAt(v time.Time) *WindsurfAccountUpdate {
	_u.mutation.SetMaintainedAt(v)
	return _u
}

// SetNillableMaintainedAt sets the "maintained_at" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillableMaintainedAt(v *time.Time) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetMaintainedAt(*v)
	}
	return _u
}

// SetStatusUpdatedBy sets the "status_updated_by" field.
func (_u *WindsurfAccountUpdate) SetStatusUpdatedBy(v int64) *WindsurfAccountUpdate {
	_u.mutation.ResetStatusUpdatedBy()
	_u.mutation.SetStatusUpdatedBy(v)
	return _u
}

// SetNillableStatusUpdatedBy sets the "status_updated_by" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillableStatusUpdatedBy(v *int64) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetStatusUpdatedBy(*v)
	}
	return _u
}

// AddStatusUpdatedBy adds value to the "status_updated_by" field.
func (_u *WindsurfAccountUpdate) AddStatusUpdatedBy(v int64) *WindsurfAccountUpdate {
	_u.mutation.AddStatusUpdatedBy(v)
	return _u
}

// ClearStatusUpdatedBy clears the value of the "status_updated_by" field.
func (_u *WindsurfAccountUpdate) ClearStatusUpdatedBy() *WindsurfAccountUpdate {
	_u.mutation.ClearStatusUpdatedBy()
	return _u
}

// SetStatusUpdatedAt sets the "status_updated_at" field.
func (_u *WindsurfAccountUpdate) SetStatusUpdatedAt(v time.Time) *WindsurfAccountUpdate {
	_u.mutation.SetStatusUpdatedAt(v)
	return _u
}

// SetNillableStatusUpdatedAt sets the "status_updated_at" field if the given value is not nil.
func (_u *WindsurfAccountUpdate) SetNillableStatusUpdatedAt(v *time.Time) *WindsurfAccountUpdate {
	if v != nil {
		_u.SetStatusUpdatedAt(*v)
	}
	return _u
}

// ClearStatusUpdatedAt clears the value of the "status_updated_at" field.
func (_u *WindsurfAccountUpdate) ClearStatusUpdatedAt() *WindsurfAccountUpdate {
	_u.mutation.ClearStatusUpdatedAt()
	return _u
}

// Mutation returns the WindsurfAccountMutation object of the builder.
func (_u *WindsurfAccountUpdate) Mutation() *WindsurfAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WindsurfAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WindsurfAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WindsurfAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WindsurfAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WindsurfAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := windsurfaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WindsurfAccountUpdate) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := windsurfaccount.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "WindsurfAccount.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordEncrypted(); ok {
		if err := windsurfaccount.PasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "password_encrypted", err: fmt.Errorf(`ent: validator failed for field "WindsurfAccount.password_encrypted": %w`, err)}
		}
	}
	return nil
}

func (_u *WindsurfAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(windsurfaccount.Table, windsurfaccount.Columns, sqlgraph.NewFieldSpec(windsurfaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(windsurfaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(windsurfaccount.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(windsurfaccount.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(windsurfaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaintainedBy(); ok {
		_spec.SetField(windsurfaccount.FieldMaintainedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaintainedBy(); ok {
		_spec.AddField(windsurfaccount.FieldMaintainedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaintainedAt(); ok {
		_spec.SetField(windsurfaccount.FieldMaintainedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StatusUpdatedBy(); ok {
		_spec.SetField(windsurfaccount.FieldStatusUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatusUpdatedBy(); ok {
		_spec.AddField(windsurfaccount.FieldStatusUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.StatusUpdatedByCleared() {
		_spec.ClearField(windsurfaccount.FieldStatusUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.StatusUpdatedAt(); ok {
		_spec.SetField(windsurfaccount.FieldStatusUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StatusUpdatedAtCleared() {
		_spec.ClearField(windsurfaccount.FieldStatusUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{windsurfaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WindsurfAccountUpdateOne is the builder for updating a single WindsurfAccount entity.
type WindsurfAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WindsurfAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WindsurfAccountUpdateOne) SetUpdatedAt(v time.Time) *WindsurfAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" field.
func (_u *WindsurfAccountUpdateOne) SetAccount(v string) *WindsurfAccountUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillableAccount(v *string) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *WindsurfAccountUpdateOne) SetPasswordEncrypted(v string) *WindsurfAccountUpdateOne {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillablePasswordEncrypted(v *string) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WindsurfAccountUpdateOne) SetEnabled(v bool) *WindsurfAccountUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillableEnabled(v *bool) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMaintainedBy sets the "maintained_by" field.
func (_u *WindsurfAccountUpdateOne) SetMaintainedBy(v int64) *WindsurfAccountUpdateOne {
	_u.mutation.ResetMaintainedBy()
	_u.mutation.SetMaintainedBy(v)
	return _u
}

// SetNillableMaintainedBy sets the "maintained_by" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillableMaintainedBy(v *int64) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetMaintainedBy(*v)
	}
	return _u
}

// AddMaintainedBy adds value to the "maintained_by" field.
func (_u *WindsurfAccountUpdateOne) AddMaintainedBy(v int64) *WindsurfAccountUpdateOne {
	_u.mutation.AddMaintainedBy(v)
	return _u
}

// SetMaintainedAt sets the "maintained_at" field.
func (_u *WindsurfAccountUpdateOne) SetMaintainedAt(v time.Time) *WindsurfAccountUpdateOne {
	_u.mutation.SetMaintainedAt(v)
	return _u
}

// SetNillableMaintainedAt sets the "maintained_at" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillableMaintainedAt(v *time.Time) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetMaintainedAt(*v)
	}
	return _u
}

// SetStatusUpdatedBy sets the "status_updated_by" field.
func (_u *WindsurfAccountUpdateOne) SetStatusUpdatedBy(v int64) *WindsurfAccountUpdateOne {
	_u.mutation.ResetStatusUpdatedBy()
	_u.mutation.SetStatusUpdatedBy(v)
	return _u
}

// SetNillableStatusUpdatedBy sets the "status_updated_by" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillableStatusUpdatedBy(v *int64) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetStatusUpdatedBy(*v)
	}
	return _u
}

// AddStatusUpdatedBy adds value to the "status_updated_by" field.
func (_u *WindsurfAccountUpdateOne) AddStatusUpdatedBy(v int64) *WindsurfAccountUpdateOne {
	_u.mutation.AddStatusUpdatedBy(v)
	return _u
}

// ClearStatusUpdatedBy clears the value of the "status_updated_by" field.
func (_u *WindsurfAccountUpdateOne) ClearStatusUpdatedBy() *WindsurfAccountUpdateOne {
	_u.mutation.ClearStatusUpdatedBy()
	return _u
}

// SetStatusUpdatedAt sets the "status_updated_at" field.
func (_u *WindsurfAccountUpdateOne) SetStatusUpdatedAt(v time.Time) *WindsurfAccountUpdateOne {
	_u.mutation.SetStatusUpdatedAt(v)
	return _u
}

// SetNillableStatusUpdatedAt sets the "status_updated_at" field if the given value is not nil.
func (_u *WindsurfAccountUpdateOne) SetNillableStatusUpdatedAt(v *time.Time) *WindsurfAccountUpdateOne {
	if v != nil {
		_u.SetStatusUpdatedAt(*v)
	}
	return _u
}

// ClearStatusUpdatedAt clears the value of the "status_updated_at" field.
func (_u *WindsurfAccountUpdateOne) ClearStatusUpdatedAt() *WindsurfAccountUpdateOne {
	_u.mutation.ClearStatusUpdatedAt()
	return _u
}

// Mutation returns the WindsurfAccountMutation object of the builder.
func (_u *WindsurfAccountUpdateOne) Mutation() *WindsurfAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the WindsurfAccountUpdate builder.
func (_u *WindsurfAccountUpdateOne) Where(ps ...predicate.WindsurfAccount) *WindsurfAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WindsurfAccountUpdateOne) Select(field string, fields ...string) *WindsurfAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WindsurfAccount entity.
func (_u *WindsurfAccountUpdateOne) Save(ctx context.Context) (*WindsurfAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WindsurfAccountUpdateOne) SaveX(ctx context.Context) *WindsurfAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WindsurfAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WindsurfAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WindsurfAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := windsurfaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WindsurfAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := windsurfaccount.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "WindsurfAccount.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordEncrypted(); ok {
		if err := windsurfaccount.PasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "password_encrypted", err: fmt.Errorf(`ent: validator failed for field "WindsurfAccount.password_encrypted": %w`, err)}
		}
	}
	return nil
}

func (_u *WindsurfAccountUpdateOne) sqlSave(ctx context.Context) (_node *WindsurfAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(windsurfaccount.Table, windsurfaccount.Columns, sqlgraph.NewFieldSpec(windsurfaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WindsurfAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, windsurfaccount.FieldID)
		for _, f := range fields {
			if !windsurfaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != windsurfaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(windsurfaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(windsurfaccount.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(windsurfaccount.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(windsurfaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaintainedBy(); ok {
		_spec.SetField(windsurfaccount.FieldMaintainedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaintainedBy(); ok {
		_spec.AddField(windsurfaccount.FieldMaintainedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MaintainedAt(); ok {
		_spec.SetField(windsurfaccount.FieldMaintainedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StatusUpdatedBy(); ok {
		_spec.SetField(windsurfaccount.FieldStatusUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatusUpdatedBy(); ok {
		_spec.AddField(windsurfaccount.FieldStatusUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.StatusUpdatedByCleared() {
		_spec.ClearField(windsurfaccount.FieldStatusUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.StatusUpdatedAt(); ok {
		_spec.SetField(windsurfaccount.FieldStatusUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StatusUpdatedAtCleared() {
		_spec.ClearField(windsurfaccount.FieldStatusUpdatedAt, field.TypeTime)
	}
	_node = &WindsurfAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{windsurfaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
