// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/zenxiangliyuprize"
	"github.com/Wei-Shaw/sub2api/ent/zenxiangliyurecord"
)

// ZenxiangLiyuRecordUpdate is the builder for updating ZenxiangLiyuRecord entities.
type ZenxiangLiyuRecordUpdate struct {
	config
	hooks    []Hook
	mutation *ZenxiangLiyuRecordMutation
}

// Where appends a list predicates to the ZenxiangLiyuRecordUpdate builder.
func (_u *ZenxiangLiyuRecordUpdate) Where(ps ...predicate.ZenxiangLiyuRecord) *ZenxiangLiyuRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ZenxiangLiyuRecordUpdate) SetRequestID(v string) *ZenxiangLiyuRecordUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableRequestID(v *string) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ZenxiangLiyuRecordUpdate) SetUserID(v int64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableUserID(v *int64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlayDate sets the "play_date" field.
func (_u *ZenxiangLiyuRecordUpdate) SetPlayDate(v time.Time) *ZenxiangLiyuRecordUpdate {
	_u.mutation.SetPlayDate(v)
	return _u
}

// SetNillablePlayDate sets the "play_date" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillablePlayDate(v *time.Time) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetPlayDate(*v)
	}
	return _u
}

// SetTicketAmount sets the "ticket_amount" field.
func (_u *ZenxiangLiyuRecordUpdate) SetTicketAmount(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetTicketAmount()
	_u.mutation.SetTicketAmount(v)
	return _u
}

// SetNillableTicketAmount sets the "ticket_amount" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableTicketAmount(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetTicketAmount(*v)
	}
	return _u
}

// AddTicketAmount adds value to the "ticket_amount" field.
func (_u *ZenxiangLiyuRecordUpdate) AddTicketAmount(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddTicketAmount(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ZenxiangLiyuRecordUpdate) SetRewardAmount(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableRewardAmount(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ZenxiangLiyuRecordUpdate) AddRewardAmount(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetUserNetAmount sets the "user_net_amount" field.
func (_u *ZenxiangLiyuRecordUpdate) SetUserNetAmount(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetUserNetAmount()
	_u.mutation.SetUserNetAmount(v)
	return _u
}

// SetNillableUserNetAmount sets the "user_net_amount" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableUserNetAmount(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetUserNetAmount(*v)
	}
	return _u
}

// AddUserNetAmount adds value to the "user_net_amount" field.
func (_u *ZenxiangLiyuRecordUpdate) AddUserNetAmount(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddUserNetAmount(v)
	return _u
}

// SetSystemRevenue sets the "system_revenue" field.
func (_u *ZenxiangLiyuRecordUpdate) SetSystemRevenue(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetSystemRevenue()
	_u.mutation.SetSystemRevenue(v)
	return _u
}

// SetNillableSystemRevenue sets the "system_revenue" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableSystemRevenue(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetSystemRevenue(*v)
	}
	return _u
}

// AddSystemRevenue adds value to the "system_revenue" field.
func (_u *ZenxiangLiyuRecordUpdate) AddSystemRevenue(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddSystemRevenue(v)
	return _u
}

// SetSystemExpense sets the "system_expense" field.
func (_u *ZenxiangLiyuRecordUpdate) SetSystemExpense(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetSystemExpense()
	_u.mutation.SetSystemExpense(v)
	return _u
}

// SetNillableSystemExpense sets the "system_expense" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableSystemExpense(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetSystemExpense(*v)
	}
	return _u
}

// AddSystemExpense adds value to the "system_expense" field.
func (_u *ZenxiangLiyuRecordUpdate) AddSystemExpense(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddSystemExpense(v)
	return _u
}

// SetSystemProfit sets the "system_profit" field.
func (_u *ZenxiangLiyuRecordUpdate) SetSystemProfit(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetSystemProfit()
	_u.mutation.SetSystemProfit(v)
	return _u
}

// SetNillableSystemProfit sets the "system_profit" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableSystemProfit(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetSystemProfit(*v)
	}
	return _u
}

// AddSystemProfit adds value to the "system_profit" field.
func (_u *ZenxiangLiyuRecordUpdate) AddSystemProfit(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddSystemProfit(v)
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *ZenxiangLiyuRecordUpdate) SetPrizeID(v int64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillablePrizeID(v *int64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (_u *ZenxiangLiyuRecordUpdate) ClearPrizeID() *ZenxiangLiyuRecordUpdate {
	_u.mutation.ClearPrizeID()
	return _u
}

// SetPrizeNameSnapshot sets the "prize_name_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdate) SetPrizeNameSnapshot(v string) *ZenxiangLiyuRecordUpdate {
	_u.mutation.SetPrizeNameSnapshot(v)
	return _u
}

// SetNillablePrizeNameSnapshot sets the "prize_name_snapshot" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillablePrizeNameSnapshot(v *string) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetPrizeNameSnapshot(*v)
	}
	return _u
}

// SetProbabilitySnapshot sets the "probability_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdate) SetProbabilitySnapshot(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetProbabilitySnapshot()
	_u.mutation.SetProbabilitySnapshot(v)
	return _u
}

// SetNillableProbabilitySnapshot sets the "probability_snapshot" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableProbabilitySnapshot(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetProbabilitySnapshot(*v)
	}
	return _u
}

// AddProbabilitySnapshot adds value to the "probability_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdate) AddProbabilitySnapshot(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddProbabilitySnapshot(v)
	return _u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdate) SetConfigSnapshot(v jsontext.Value) *ZenxiangLiyuRecordUpdate {
	_u.mutation.SetConfigSnapshot(v)
	return _u
}

// AppendConfigSnapshot appends value to the "config_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdate) AppendConfigSnapshot(v jsontext.Value) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AppendConfigSnapshot(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *ZenxiangLiyuRecordUpdate) SetBalanceBefore(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableBalanceBefore(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *ZenxiangLiyuRecordUpdate) AddBalanceBefore(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfterTicket sets the "balance_after_ticket" field.
func (_u *ZenxiangLiyuRecordUpdate) SetBalanceAfterTicket(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetBalanceAfterTicket()
	_u.mutation.SetBalanceAfterTicket(v)
	return _u
}

// SetNillableBalanceAfterTicket sets the "balance_after_ticket" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableBalanceAfterTicket(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetBalanceAfterTicket(*v)
	}
	return _u
}

// AddBalanceAfterTicket adds value to the "balance_after_ticket" field.
func (_u *ZenxiangLiyuRecordUpdate) AddBalanceAfterTicket(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddBalanceAfterTicket(v)
	return _u
}

// SetBalanceAfterReward sets the "balance_after_reward" field.
func (_u *ZenxiangLiyuRecordUpdate) SetBalanceAfterReward(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.ResetBalanceAfterReward()
	_u.mutation.SetBalanceAfterReward(v)
	return _u
}

// SetNillableBalanceAfterReward sets the "balance_after_reward" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdate) SetNillableBalanceAfterReward(v *float64) *ZenxiangLiyuRecordUpdate {
	if v != nil {
		_u.SetBalanceAfterReward(*v)
	}
	return _u
}

// AddBalanceAfterReward adds value to the "balance_after_reward" field.
func (_u *ZenxiangLiyuRecordUpdate) AddBalanceAfterReward(v float64) *ZenxiangLiyuRecordUpdate {
	_u.mutation.AddBalanceAfterReward(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ZenxiangLiyuRecordUpdate) SetUser(v *User) *ZenxiangLiyuRecordUpdate {
	return _u.SetUserID(v.ID)
}

// SetPrize sets the "prize" edge to the ZenxiangLiyuPrize entity.
func (_u *ZenxiangLiyuRecordUpdate) SetPrize(v *ZenxiangLiyuPrize) *ZenxiangLiyuRecordUpdate {
	return _u.SetPrizeID(v.ID)
}

// Mutation returns the ZenxiangLiyuRecordMutation object of the builder.
func (_u *ZenxiangLiyuRecordUpdate) Mutation() *ZenxiangLiyuRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ZenxiangLiyuRecordUpdate) ClearUser() *ZenxiangLiyuRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPrize clears the "prize" edge to the ZenxiangLiyuPrize entity.
func (_u *ZenxiangLiyuRecordUpdate) ClearPrize() *ZenxiangLiyuRecordUpdate {
	_u.mutation.ClearPrize()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ZenxiangLiyuRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZenxiangLiyuRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ZenxiangLiyuRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZenxiangLiyuRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZenxiangLiyuRecordUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := zenxiangliyurecord.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ZenxiangLiyuRecord.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeNameSnapshot(); ok {
		if err := zenxiangliyurecord.PrizeNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "prize_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "ZenxiangLiyuRecord.prize_name_snapshot": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ZenxiangLiyuRecord.user"`)
	}
	return nil
}

func (_u *ZenxiangLiyuRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zenxiangliyurecord.Table, zenxiangliyurecord.Columns, sqlgraph.NewFieldSpec(zenxiangliyurecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(zenxiangliyurecord.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayDate(); ok {
		_spec.SetField(zenxiangliyurecord.FieldPlayDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TicketAmount(); ok {
		_spec.SetField(zenxiangliyurecord.FieldTicketAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTicketAmount(); ok {
		_spec.AddField(zenxiangliyurecord.FieldTicketAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(zenxiangliyurecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(zenxiangliyurecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UserNetAmount(); ok {
		_spec.SetField(zenxiangliyurecord.FieldUserNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUserNetAmount(); ok {
		_spec.AddField(zenxiangliyurecord.FieldUserNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SystemRevenue(); ok {
		_spec.SetField(zenxiangliyurecord.FieldSystemRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSystemRevenue(); ok {
		_spec.AddField(zenxiangliyurecord.FieldSystemRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SystemExpense(); ok {
		_spec.SetField(zenxiangliyurecord.FieldSystemExpense, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSystemExpense(); ok {
		_spec.AddField(zenxiangliyurecord.FieldSystemExpense, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SystemProfit(); ok {
		_spec.SetField(zenxiangliyurecord.FieldSystemProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSystemProfit(); ok {
		_spec.AddField(zenxiangliyurecord.FieldSystemProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PrizeNameSnapshot(); ok {
		_spec.SetField(zenxiangliyurecord.FieldPrizeNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbabilitySnapshot(); ok {
		_spec.SetField(zenxiangliyurecord.FieldProbabilitySnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProbabilitySnapshot(); ok {
		_spec.AddField(zenxiangliyurecord.FieldProbabilitySnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConfigSnapshot(); ok {
		_spec.SetField(zenxiangliyurecord.FieldConfigSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfigSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, zenxiangliyurecord.FieldConfigSnapshot, value)
		})
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(zenxiangliyurecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(zenxiangliyurecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfterTicket(); ok {
		_spec.SetField(zenxiangliyurecord.FieldBalanceAfterTicket, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfterTicket(); ok {
		_spec.AddField(zenxiangliyurecord.FieldBalanceAfterTicket, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfterReward(); ok {
		_spec.SetField(zenxiangliyurecord.FieldBalanceAfterReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfterReward(); ok {
		_spec.AddField(zenxiangliyurecord.FieldBalanceAfterReward, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.UserTable,
			Columns: []string{zenxiangliyurecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.UserTable,
			Columns: []string{zenxiangliyurecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.PrizeTable,
			Columns: []string{zenxiangliyurecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(zenxiangliyuprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.PrizeTable,
			Columns: []string{zenxiangliyurecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(zenxiangliyuprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zenxiangliyurecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ZenxiangLiyuRecordUpdateOne is the builder for updating a single ZenxiangLiyuRecord entity.
type ZenxiangLiyuRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ZenxiangLiyuRecordMutation
}

// SetRequestID sets the "request_id" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetRequestID(v string) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableRequestID(v *string) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetUserID(v int64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableUserID(v *int64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlayDate sets the "play_date" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetPlayDate(v time.Time) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.SetPlayDate(v)
	return _u
}

// SetNillablePlayDate sets the "play_date" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillablePlayDate(v *time.Time) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetPlayDate(*v)
	}
	return _u
}

// SetTicketAmount sets the "ticket_amount" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetTicketAmount(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetTicketAmount()
	_u.mutation.SetTicketAmount(v)
	return _u
}

// SetNillableTicketAmount sets the "ticket_amount" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableTicketAmount(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetTicketAmount(*v)
	}
	return _u
}

// AddTicketAmount adds value to the "ticket_amount" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddTicketAmount(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddTicketAmount(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetRewardAmount(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableRewardAmount(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddRewardAmount(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetUserNetAmount sets the "user_net_amount" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetUserNetAmount(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetUserNetAmount()
	_u.mutation.SetUserNetAmount(v)
	return _u
}

// SetNillableUserNetAmount sets the "user_net_amount" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableUserNetAmount(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetUserNetAmount(*v)
	}
	return _u
}

// AddUserNetAmount adds value to the "user_net_amount" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddUserNetAmount(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddUserNetAmount(v)
	return _u
}

// SetSystemRevenue sets the "system_revenue" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetSystemRevenue(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetSystemRevenue()
	_u.mutation.SetSystemRevenue(v)
	return _u
}

// SetNillableSystemRevenue sets the "system_revenue" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableSystemRevenue(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetSystemRevenue(*v)
	}
	return _u
}

// AddSystemRevenue adds value to the "system_revenue" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddSystemRevenue(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddSystemRevenue(v)
	return _u
}

// SetSystemExpense sets the "system_expense" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetSystemExpense(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetSystemExpense()
	_u.mutation.SetSystemExpense(v)
	return _u
}

// SetNillableSystemExpense sets the "system_expense" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableSystemExpense(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetSystemExpense(*v)
	}
	return _u
}

// AddSystemExpense adds value to the "system_expense" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddSystemExpense(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddSystemExpense(v)
	return _u
}

// SetSystemProfit sets the "system_profit" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetSystemProfit(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetSystemProfit()
	_u.mutation.SetSystemProfit(v)
	return _u
}

// SetNillableSystemProfit sets the "system_profit" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableSystemProfit(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetSystemProfit(*v)
	}
	return _u
}

// AddSystemProfit adds value to the "system_profit" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddSystemProfit(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddSystemProfit(v)
	return _u
}

// SetPrizeID sets the "prize_id" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetPrizeID(v int64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.SetPrizeID(v)
	return _u
}

// SetNillablePrizeID sets the "prize_id" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillablePrizeID(v *int64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetPrizeID(*v)
	}
	return _u
}

// ClearPrizeID clears the value of the "prize_id" field.
func (_u *ZenxiangLiyuRecordUpdateOne) ClearPrizeID() *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ClearPrizeID()
	return _u
}

// SetPrizeNameSnapshot sets the "prize_name_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetPrizeNameSnapshot(v string) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.SetPrizeNameSnapshot(v)
	return _u
}

// SetNillablePrizeNameSnapshot sets the "prize_name_snapshot" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillablePrizeNameSnapshot(v *string) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetPrizeNameSnapshot(*v)
	}
	return _u
}

// SetProbabilitySnapshot sets the "probability_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetProbabilitySnapshot(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetProbabilitySnapshot()
	_u.mutation.SetProbabilitySnapshot(v)
	return _u
}

// SetNillableProbabilitySnapshot sets the "probability_snapshot" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableProbabilitySnapshot(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetProbabilitySnapshot(*v)
	}
	return _u
}

// AddProbabilitySnapshot adds value to the "probability_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddProbabilitySnapshot(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddProbabilitySnapshot(v)
	return _u
}

// SetConfigSnapshot sets the "config_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetConfigSnapshot(v jsontext.Value) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.SetConfigSnapshot(v)
	return _u
}

// AppendConfigSnapshot appends value to the "config_snapshot" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AppendConfigSnapshot(v jsontext.Value) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AppendConfigSnapshot(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetBalanceBefore(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableBalanceBefore(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddBalanceBefore(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfterTicket sets the "balance_after_ticket" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetBalanceAfterTicket(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetBalanceAfterTicket()
	_u.mutation.SetBalanceAfterTicket(v)
	return _u
}

// SetNillableBalanceAfterTicket sets the "balance_after_ticket" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableBalanceAfterTicket(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetBalanceAfterTicket(*v)
	}
	return _u
}

// AddBalanceAfterTicket adds value to the "balance_after_ticket" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddBalanceAfterTicket(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddBalanceAfterTicket(v)
	return _u
}

// SetBalanceAfterReward sets the "balance_after_reward" field.
func (_u *ZenxiangLiyuRecordUpdateOne) SetBalanceAfterReward(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ResetBalanceAfterReward()
	_u.mutation.SetBalanceAfterReward(v)
	return _u
}

// SetNillableBalanceAfterReward sets the "balance_after_reward" field if the given value is not nil.
func (_u *ZenxiangLiyuRecordUpdateOne) SetNillableBalanceAfterReward(v *float64) *ZenxiangLiyuRecordUpdateOne {
	if v != nil {
		_u.SetBalanceAfterReward(*v)
	}
	return _u
}

// AddBalanceAfterReward adds value to the "balance_after_reward" field.
func (_u *ZenxiangLiyuRecordUpdateOne) AddBalanceAfterReward(v float64) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.AddBalanceAfterReward(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ZenxiangLiyuRecordUpdateOne) SetUser(v *User) *ZenxiangLiyuRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPrize sets the "prize" edge to the ZenxiangLiyuPrize entity.
func (_u *ZenxiangLiyuRecordUpdateOne) SetPrize(v *ZenxiangLiyuPrize) *ZenxiangLiyuRecordUpdateOne {
	return _u.SetPrizeID(v.ID)
}

// Mutation returns the ZenxiangLiyuRecordMutation object of the builder.
func (_u *ZenxiangLiyuRecordUpdateOne) Mutation() *ZenxiangLiyuRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ZenxiangLiyuRecordUpdateOne) ClearUser() *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPrize clears the "prize" edge to the ZenxiangLiyuPrize entity.
func (_u *ZenxiangLiyuRecordUpdateOne) ClearPrize() *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.ClearPrize()
	return _u
}

// Where appends a list predicates to the ZenxiangLiyuRecordUpdate builder.
func (_u *ZenxiangLiyuRecordUpdateOne) Where(ps ...predicate.ZenxiangLiyuRecord) *ZenxiangLiyuRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ZenxiangLiyuRecordUpdateOne) Select(field string, fields ...string) *ZenxiangLiyuRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ZenxiangLiyuRecord entity.
func (_u *ZenxiangLiyuRecordUpdateOne) Save(ctx context.Context) (*ZenxiangLiyuRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZenxiangLiyuRecordUpdateOne) SaveX(ctx context.Context) *ZenxiangLiyuRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ZenxiangLiyuRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZenxiangLiyuRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZenxiangLiyuRecordUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := zenxiangliyurecord.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ZenxiangLiyuRecord.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeNameSnapshot(); ok {
		if err := zenxiangliyurecord.PrizeNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "prize_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "ZenxiangLiyuRecord.prize_name_snapshot": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ZenxiangLiyuRecord.user"`)
	}
	return nil
}

func (_u *ZenxiangLiyuRecordUpdateOne) sqlSave(ctx context.Context) (_node *ZenxiangLiyuRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zenxiangliyurecord.Table, zenxiangliyurecord.Columns, sqlgraph.NewFieldSpec(zenxiangliyurecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ZenxiangLiyuRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, zenxiangliyurecord.FieldID)
		for _, f := range fields {
			if !zenxiangliyurecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != zenxiangliyurecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(zenxiangliyurecord.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayDate(); ok {
		_spec.SetField(zenxiangliyurecord.FieldPlayDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TicketAmount(); ok {
		_spec.SetField(zenxiangliyurecord.FieldTicketAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTicketAmount(); ok {
		_spec.AddField(zenxiangliyurecord.FieldTicketAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(zenxiangliyurecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(zenxiangliyurecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UserNetAmount(); ok {
		_spec.SetField(zenxiangliyurecord.FieldUserNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUserNetAmount(); ok {
		_spec.AddField(zenxiangliyurecord.FieldUserNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SystemRevenue(); ok {
		_spec.SetField(zenxiangliyurecord.FieldSystemRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSystemRevenue(); ok {
		_spec.AddField(zenxiangliyurecord.FieldSystemRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SystemExpense(); ok {
		_spec.SetField(zenxiangliyurecord.FieldSystemExpense, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSystemExpense(); ok {
		_spec.AddField(zenxiangliyurecord.FieldSystemExpense, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SystemProfit(); ok {
		_spec.SetField(zenxiangliyurecord.FieldSystemProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSystemProfit(); ok {
		_spec.AddField(zenxiangliyurecord.FieldSystemProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PrizeNameSnapshot(); ok {
		_spec.SetField(zenxiangliyurecord.FieldPrizeNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbabilitySnapshot(); ok {
		_spec.SetField(zenxiangliyurecord.FieldProbabilitySnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProbabilitySnapshot(); ok {
		_spec.AddField(zenxiangliyurecord.FieldProbabilitySnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConfigSnapshot(); ok {
		_spec.SetField(zenxiangliyurecord.FieldConfigSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfigSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, zenxiangliyurecord.FieldConfigSnapshot, value)
		})
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(zenxiangliyurecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(zenxiangliyurecord.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfterTicket(); ok {
		_spec.SetField(zenxiangliyurecord.FieldBalanceAfterTicket, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfterTicket(); ok {
		_spec.AddField(zenxiangliyurecord.FieldBalanceAfterTicket, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfterReward(); ok {
		_spec.SetField(zenxiangliyurecord.FieldBalanceAfterReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfterReward(); ok {
		_spec.AddField(zenxiangliyurecord.FieldBalanceAfterReward, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.UserTable,
			Columns: []string{zenxiangliyurecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.UserTable,
			Columns: []string{zenxiangliyurecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.PrizeTable,
			Columns: []string{zenxiangliyurecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(zenxiangliyuprize.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyurecord.PrizeTable,
			Columns: []string{zenxiangliyurecord.PrizeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(zenxiangliyuprize.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ZenxiangLiyuRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zenxiangliyurecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
