// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/zenxiangliyuusergrant"
)

// ZenxiangLiyuUserGrantUpdate is the builder for updating ZenxiangLiyuUserGrant entities.
type ZenxiangLiyuUserGrantUpdate struct {
	config
	hooks    []Hook
	mutation *ZenxiangLiyuUserGrantMutation
}

// Where appends a list predicates to the ZenxiangLiyuUserGrantUpdate builder.
func (_u *ZenxiangLiyuUserGrantUpdate) Where(ps ...predicate.ZenxiangLiyuUserGrant) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ZenxiangLiyuUserGrantUpdate) SetUpdatedAt(v time.Time) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ZenxiangLiyuUserGrantUpdate) SetUserID(v int64) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdate) SetNillableUserID(v *int64) *ZenxiangLiyuUserGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ZenxiangLiyuUserGrantUpdate) SetEnabled(v bool) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdate) SetNillableEnabled(v *bool) *ZenxiangLiyuUserGrantUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *ZenxiangLiyuUserGrantUpdate) SetGrantedBy(v int64) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdate) SetNillableGrantedBy(v *int64) *ZenxiangLiyuUserGrantUpdate {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *ZenxiangLiyuUserGrantUpdate) ClearGrantedBy() *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ZenxiangLiyuUserGrantUpdate) SetNotes(v string) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdate) SetNillableNotes(v *string) *ZenxiangLiyuUserGrantUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdate) SetUser(v *User) *ZenxiangLiyuUserGrantUpdate {
	return _u.SetUserID(v.ID)
}

// SetGrantedByUserID sets the "granted_by_user" edge to the User entity by ID.
func (_u *ZenxiangLiyuUserGrantUpdate) SetGrantedByUserID(id int64) *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.SetGrantedByUserID(id)
	return _u
}

// SetNillableGrantedByUserID sets the "granted_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdate) SetNillableGrantedByUserID(id *int64) *ZenxiangLiyuUserGrantUpdate {
	if id != nil {
		_u = _u.SetGrantedByUserID(*id)
	}
	return _u
}

// SetGrantedByUser sets the "granted_by_user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdate) SetGrantedByUser(v *User) *ZenxiangLiyuUserGrantUpdate {
	return _u.SetGrantedByUserID(v.ID)
}

// Mutation returns the ZenxiangLiyuUserGrantMutation object of the builder.
func (_u *ZenxiangLiyuUserGrantUpdate) Mutation() *ZenxiangLiyuUserGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdate) ClearUser() *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGrantedByUser clears the "granted_by_user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdate) ClearGrantedByUser() *ZenxiangLiyuUserGrantUpdate {
	_u.mutation.ClearGrantedByUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ZenxiangLiyuUserGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZenxiangLiyuUserGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ZenxiangLiyuUserGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZenxiangLiyuUserGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ZenxiangLiyuUserGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := zenxiangliyuusergrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZenxiangLiyuUserGrantUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ZenxiangLiyuUserGrant.user"`)
	}
	return nil
}

func (_u *ZenxiangLiyuUserGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zenxiangliyuusergrant.Table, zenxiangliyuusergrant.Columns, sqlgraph.NewFieldSpec(zenxiangliyuusergrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyuusergrant.UserTable,
			Columns: []string{zenxiangliyuusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyuusergrant.UserTable,
			Columns: []string{zenxiangliyuusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   zenxiangliyuusergrant.GrantedByUserTable,
			Columns: []string{zenxiangliyuusergrant.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   zenxiangliyuusergrant.GrantedByUserTable,
			Columns: []string{zenxiangliyuusergrant.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zenxiangliyuusergrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ZenxiangLiyuUserGrantUpdateOne is the builder for updating a single ZenxiangLiyuUserGrant entity.
type ZenxiangLiyuUserGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ZenxiangLiyuUserGrantMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetUpdatedAt(v time.Time) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetUserID(v int64) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetNillableUserID(v *int64) *ZenxiangLiyuUserGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetEnabled(v bool) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetNillableEnabled(v *bool) *ZenxiangLiyuUserGrantUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetGrantedBy(v int64) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetNillableGrantedBy(v *int64) *ZenxiangLiyuUserGrantUpdateOne {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *ZenxiangLiyuUserGrantUpdateOne) ClearGrantedBy() *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetNotes(v string) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetNillableNotes(v *string) *ZenxiangLiyuUserGrantUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetUser(v *User) *ZenxiangLiyuUserGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGrantedByUserID sets the "granted_by_user" edge to the User entity by ID.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetGrantedByUserID(id int64) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.SetGrantedByUserID(id)
	return _u
}

// SetNillableGrantedByUserID sets the "granted_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetNillableGrantedByUserID(id *int64) *ZenxiangLiyuUserGrantUpdateOne {
	if id != nil {
		_u = _u.SetGrantedByUserID(*id)
	}
	return _u
}

// SetGrantedByUser sets the "granted_by_user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SetGrantedByUser(v *User) *ZenxiangLiyuUserGrantUpdateOne {
	return _u.SetGrantedByUserID(v.ID)
}

// Mutation returns the ZenxiangLiyuUserGrantMutation object of the builder.
func (_u *ZenxiangLiyuUserGrantUpdateOne) Mutation() *ZenxiangLiyuUserGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdateOne) ClearUser() *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGrantedByUser clears the "granted_by_user" edge to the User entity.
func (_u *ZenxiangLiyuUserGrantUpdateOne) ClearGrantedByUser() *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.ClearGrantedByUser()
	return _u
}

// Where appends a list predicates to the ZenxiangLiyuUserGrantUpdate builder.
func (_u *ZenxiangLiyuUserGrantUpdateOne) Where(ps ...predicate.ZenxiangLiyuUserGrant) *ZenxiangLiyuUserGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ZenxiangLiyuUserGrantUpdateOne) Select(field string, fields ...string) *ZenxiangLiyuUserGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ZenxiangLiyuUserGrant entity.
func (_u *ZenxiangLiyuUserGrantUpdateOne) Save(ctx context.Context) (*ZenxiangLiyuUserGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ZenxiangLiyuUserGrantUpdateOne) SaveX(ctx context.Context) *ZenxiangLiyuUserGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ZenxiangLiyuUserGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ZenxiangLiyuUserGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ZenxiangLiyuUserGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := zenxiangliyuusergrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ZenxiangLiyuUserGrantUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ZenxiangLiyuUserGrant.user"`)
	}
	return nil
}

func (_u *ZenxiangLiyuUserGrantUpdateOne) sqlSave(ctx context.Context) (_node *ZenxiangLiyuUserGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(zenxiangliyuusergrant.Table, zenxiangliyuusergrant.Columns, sqlgraph.NewFieldSpec(zenxiangliyuusergrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ZenxiangLiyuUserGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, zenxiangliyuusergrant.FieldID)
		for _, f := range fields {
			if !zenxiangliyuusergrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != zenxiangliyuusergrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyuusergrant.UserTable,
			Columns: []string{zenxiangliyuusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyuusergrant.UserTable,
			Columns: []string{zenxiangliyuusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   zenxiangliyuusergrant.GrantedByUserTable,
			Columns: []string{zenxiangliyuusergrant.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   zenxiangliyuusergrant.GrantedByUserTable,
			Columns: []string{zenxiangliyuusergrant.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ZenxiangLiyuUserGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{zenxiangliyuusergrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
