// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/zenxiangliyuusergrant"
)

// ZenxiangLiyuUserGrantCreate is the builder for creating a ZenxiangLiyuUserGrant entity.
type ZenxiangLiyuUserGrantCreate struct {
	config
	mutation *ZenxiangLiyuUserGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ZenxiangLiyuUserGrantCreate) SetCreatedAt(v time.Time) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ZenxiangLiyuUserGrantCreate) SetNillableCreatedAt(v *time.Time) *ZenxiangLiyuUserGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ZenxiangLiyuUserGrantCreate) SetUpdatedAt(v time.Time) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ZenxiangLiyuUserGrantCreate) SetNillableUpdatedAt(v *time.Time) *ZenxiangLiyuUserGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ZenxiangLiyuUserGrantCreate) SetUserID(v int64) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ZenxiangLiyuUserGrantCreate) SetEnabled(v bool) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ZenxiangLiyuUserGrantCreate) SetNillableEnabled(v *bool) *ZenxiangLiyuUserGrantCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetGrantedBy sets the "granted_by" field.
func (_c *ZenxiangLiyuUserGrantCreate) SetGrantedBy(v int64) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetGrantedBy(v)
	return _c
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_c *ZenxiangLiyuUserGrantCreate) SetNillableGrantedBy(v *int64) *ZenxiangLiyuUserGrantCreate {
	if v != nil {
		_c.SetGrantedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ZenxiangLiyuUserGrantCreate) SetNotes(v string) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ZenxiangLiyuUserGrantCreate) SetNillableNotes(v *string) *ZenxiangLiyuUserGrantCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ZenxiangLiyuUserGrantCreate) SetUser(v *User) *ZenxiangLiyuUserGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetGrantedByUserID sets the "granted_by_user" edge to the User entity by ID.
func (_c *ZenxiangLiyuUserGrantCreate) SetGrantedByUserID(id int64) *ZenxiangLiyuUserGrantCreate {
	_c.mutation.SetGrantedByUserID(id)
	return _c
}

// SetNillableGrantedByUserID sets the "granted_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *ZenxiangLiyuUserGrantCreate) SetNillableGrantedByUserID(id *int64) *ZenxiangLiyuUserGrantCreate {
	if id != nil {
		_c = _c.SetGrantedByUserID(*id)
	}
	return _c
}

// SetGrantedByUser sets the "granted_by_user" edge to the User entity.
func (_c *ZenxiangLiyuUserGrantCreate) SetGrantedByUser(v *User) *ZenxiangLiyuUserGrantCreate {
	return _c.SetGrantedByUserID(v.ID)
}

// Mutation returns the ZenxiangLiyuUserGrantMutation object of the builder.
func (_c *ZenxiangLiyuUserGrantCreate) Mutation() *ZenxiangLiyuUserGrantMutation {
	return _c.mutation
}

// Save creates the ZenxiangLiyuUserGrant in the database.
func (_c *ZenxiangLiyuUserGrantCreate) Save(ctx context.Context) (*ZenxiangLiyuUserGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ZenxiangLiyuUserGrantCreate) SaveX(ctx context.Context) *ZenxiangLiyuUserGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZenxiangLiyuUserGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZenxiangLiyuUserGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ZenxiangLiyuUserGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := zenxiangliyuusergrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := zenxiangliyuusergrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := zenxiangliyuusergrant.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := zenxiangliyuusergrant.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ZenxiangLiyuUserGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ZenxiangLiyuUserGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ZenxiangLiyuUserGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ZenxiangLiyuUserGrant.user_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ZenxiangLiyuUserGrant.enabled"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "ZenxiangLiyuUserGrant.notes"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ZenxiangLiyuUserGrant.user"`)}
	}
	return nil
}

func (_c *ZenxiangLiyuUserGrantCreate) sqlSave(ctx context.Context) (*ZenxiangLiyuUserGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ZenxiangLiyuUserGrantCreate) createSpec() (*ZenxiangLiyuUserGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &ZenxiangLiyuUserGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(zenxiangliyuusergrant.Table, sqlgraph.NewFieldSpec(zenxiangliyuusergrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(zenxiangliyuusergrant.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   zenxiangliyuusergrant.UserTable,
			Columns: []string{zenxiangliyuusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GrantedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   zenxiangliyuusergrant.GrantedByUserTable,
			Columns: []string{zenxiangliyuusergrant.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GrantedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ZenxiangLiyuUserGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZenxiangLiyuUserGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ZenxiangLiyuUserGrantCreate) OnConflict(opts ...sql.ConflictOption) *ZenxiangLiyuUserGrantUpsertOne {
	_c.conflict = opts
	return &ZenxiangLiyuUserGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ZenxiangLiyuUserGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ZenxiangLiyuUserGrantCreate) OnConflictColumns(columns ...string) *ZenxiangLiyuUserGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ZenxiangLiyuUserGrantUpsertOne{
		create: _c,
	}
}

type (
	// ZenxiangLiyuUserGrantUpsertOne is the builder for "upsert"-ing
	//  one ZenxiangLiyuUserGrant node.
	ZenxiangLiyuUserGrantUpsertOne struct {
		create *ZenxiangLiyuUserGrantCreate
	}

	// ZenxiangLiyuUserGrantUpsert is the "OnConflict" setter.
	ZenxiangLiyuUserGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ZenxiangLiyuUserGrantUpsert) SetUpdatedAt(v time.Time) *ZenxiangLiyuUserGrantUpsert {
	u.Set(zenxiangliyuusergrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsert) UpdateUpdatedAt() *ZenxiangLiyuUserGrantUpsert {
	u.SetExcluded(zenxiangliyuusergrant.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ZenxiangLiyuUserGrantUpsert) SetUserID(v int64) *ZenxiangLiyuUserGrantUpsert {
	u.Set(zenxiangliyuusergrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsert) UpdateUserID() *ZenxiangLiyuUserGrantUpsert {
	u.SetExcluded(zenxiangliyuusergrant.FieldUserID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ZenxiangLiyuUserGrantUpsert) SetEnabled(v bool) *ZenxiangLiyuUserGrantUpsert {
	u.Set(zenxiangliyuusergrant.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsert) UpdateEnabled() *ZenxiangLiyuUserGrantUpsert {
	u.SetExcluded(zenxiangliyuusergrant.FieldEnabled)
	return u
}

// SetGrantedBy sets the "granted_by" field.
func (u *ZenxiangLiyuUserGrantUpsert) SetGrantedBy(v int64) *ZenxiangLiyuUserGrantUpsert {
	u.Set(zenxiangliyuusergrant.FieldGrantedBy, v)
	return u
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsert) UpdateGrantedBy() *ZenxiangLiyuUserGrantUpsert {
	u.SetExcluded(zenxiangliyuusergrant.FieldGrantedBy)
	return u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (u *ZenxiangLiyuUserGrantUpsert) ClearGrantedBy() *ZenxiangLiyuUserGrantUpsert {
	u.SetNull(zenxiangliyuusergrant.FieldGrantedBy)
	return u
}

// SetNotes sets the "notes" field.
func (u *ZenxiangLiyuUserGrantUpsert) SetNotes(v string) *ZenxiangLiyuUserGrantUpsert {
	u.Set(zenxiangliyuusergrant.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsert) UpdateNotes() *ZenxiangLiyuUserGrantUpsert {
	u.SetExcluded(zenxiangliyuusergrant.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ZenxiangLiyuUserGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ZenxiangLiyuUserGrantUpsertOne) UpdateNewValues() *ZenxiangLiyuUserGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(zenxiangliyuusergrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ZenxiangLiyuUserGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ZenxiangLiyuUserGrantUpsertOne) Ignore() *ZenxiangLiyuUserGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZenxiangLiyuUserGrantUpsertOne) DoNothing() *ZenxiangLiyuUserGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZenxiangLiyuUserGrantCreate.OnConflict
// documentation for more info.
func (u *ZenxiangLiyuUserGrantUpsertOne) Update(set func(*ZenxiangLiyuUserGrantUpsert)) *ZenxiangLiyuUserGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZenxiangLiyuUserGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ZenxiangLiyuUserGrantUpsertOne) SetUpdatedAt(v time.Time) *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertOne) UpdateUpdatedAt() *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ZenxiangLiyuUserGrantUpsertOne) SetUserID(v int64) *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertOne) UpdateUserID() *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ZenxiangLiyuUserGrantUpsertOne) SetEnabled(v bool) *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertOne) UpdateEnabled() *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateEnabled()
	})
}

// SetGrantedBy sets the "granted_by" field.
func (u *ZenxiangLiyuUserGrantUpsertOne) SetGrantedBy(v int64) *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetGrantedBy(v)
	})
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertOne) UpdateGrantedBy() *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateGrantedBy()
	})
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (u *ZenxiangLiyuUserGrantUpsertOne) ClearGrantedBy() *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.ClearGrantedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *ZenxiangLiyuUserGrantUpsertOne) SetNotes(v string) *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertOne) UpdateNotes() *ZenxiangLiyuUserGrantUpsertOne {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *ZenxiangLiyuUserGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZenxiangLiyuUserGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZenxiangLiyuUserGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ZenxiangLiyuUserGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ZenxiangLiyuUserGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ZenxiangLiyuUserGrantCreateBulk is the builder for creating many ZenxiangLiyuUserGrant entities in bulk.
type ZenxiangLiyuUserGrantCreateBulk struct {
	config
	err      error
	builders []*ZenxiangLiyuUserGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the ZenxiangLiyuUserGrant entities in the database.
func (_c *ZenxiangLiyuUserGrantCreateBulk) Save(ctx context.Context) ([]*ZenxiangLiyuUserGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ZenxiangLiyuUserGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ZenxiangLiyuUserGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ZenxiangLiyuUserGrantCreateBulk) SaveX(ctx context.Context) []*ZenxiangLiyuUserGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ZenxiangLiyuUserGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ZenxiangLiyuUserGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ZenxiangLiyuUserGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ZenxiangLiyuUserGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ZenxiangLiyuUserGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *ZenxiangLiyuUserGrantUpsertBulk {
	_c.conflict = opts
	return &ZenxiangLiyuUserGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ZenxiangLiyuUserGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ZenxiangLiyuUserGrantCreateBulk) OnConflictColumns(columns ...string) *ZenxiangLiyuUserGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ZenxiangLiyuUserGrantUpsertBulk{
		create: _c,
	}
}

// ZenxiangLiyuUserGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of ZenxiangLiyuUserGrant nodes.
type ZenxiangLiyuUserGrantUpsertBulk struct {
	create *ZenxiangLiyuUserGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ZenxiangLiyuUserGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ZenxiangLiyuUserGrantUpsertBulk) UpdateNewValues() *ZenxiangLiyuUserGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(zenxiangliyuusergrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ZenxiangLiyuUserGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ZenxiangLiyuUserGrantUpsertBulk) Ignore() *ZenxiangLiyuUserGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ZenxiangLiyuUserGrantUpsertBulk) DoNothing() *ZenxiangLiyuUserGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ZenxiangLiyuUserGrantCreateBulk.OnConflict
// documentation for more info.
func (u *ZenxiangLiyuUserGrantUpsertBulk) Update(set func(*ZenxiangLiyuUserGrantUpsert)) *ZenxiangLiyuUserGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ZenxiangLiyuUserGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ZenxiangLiyuUserGrantUpsertBulk) SetUpdatedAt(v time.Time) *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertBulk) UpdateUpdatedAt() *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ZenxiangLiyuUserGrantUpsertBulk) SetUserID(v int64) *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertBulk) UpdateUserID() *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ZenxiangLiyuUserGrantUpsertBulk) SetEnabled(v bool) *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertBulk) UpdateEnabled() *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateEnabled()
	})
}

// SetGrantedBy sets the "granted_by" field.
func (u *ZenxiangLiyuUserGrantUpsertBulk) SetGrantedBy(v int64) *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetGrantedBy(v)
	})
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertBulk) UpdateGrantedBy() *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateGrantedBy()
	})
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (u *ZenxiangLiyuUserGrantUpsertBulk) ClearGrantedBy() *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.ClearGrantedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *ZenxiangLiyuUserGrantUpsertBulk) SetNotes(v string) *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ZenxiangLiyuUserGrantUpsertBulk) UpdateNotes() *ZenxiangLiyuUserGrantUpsertBulk {
	return u.Update(func(s *ZenxiangLiyuUserGrantUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *ZenxiangLiyuUserGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ZenxiangLiyuUserGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ZenxiangLiyuUserGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ZenxiangLiyuUserGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
