// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/zenxiangliyuprize"
	"github.com/Wei-Shaw/sub2api/ent/zenxiangliyurecord"
)

// ZenxiangLiyuRecord is the model entity for the ZenxiangLiyuRecord schema.
type ZenxiangLiyuRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PlayDate holds the value of the "play_date" field.
	PlayDate time.Time `json:"play_date,omitempty"`
	// TicketAmount holds the value of the "ticket_amount" field.
	TicketAmount float64 `json:"ticket_amount,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// UserNetAmount holds the value of the "user_net_amount" field.
	UserNetAmount float64 `json:"user_net_amount,omitempty"`
	// SystemRevenue holds the value of the "system_revenue" field.
	SystemRevenue float64 `json:"system_revenue,omitempty"`
	// SystemExpense holds the value of the "system_expense" field.
	SystemExpense float64 `json:"system_expense,omitempty"`
	// SystemProfit holds the value of the "system_profit" field.
	SystemProfit float64 `json:"system_profit,omitempty"`
	// PrizeID holds the value of the "prize_id" field.
	PrizeID *int64 `json:"prize_id,omitempty"`
	// PrizeNameSnapshot holds the value of the "prize_name_snapshot" field.
	PrizeNameSnapshot string `json:"prize_name_snapshot,omitempty"`
	// ProbabilitySnapshot holds the value of the "probability_snapshot" field.
	ProbabilitySnapshot float64 `json:"probability_snapshot,omitempty"`
	// ConfigSnapshot holds the value of the "config_snapshot" field.
	ConfigSnapshot jsontext.Value `json:"config_snapshot,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore float64 `json:"balance_before,omitempty"`
	// BalanceAfterTicket holds the value of the "balance_after_ticket" field.
	BalanceAfterTicket float64 `json:"balance_after_ticket,omitempty"`
	// BalanceAfterReward holds the value of the "balance_after_reward" field.
	BalanceAfterReward float64 `json:"balance_after_reward,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ZenxiangLiyuRecordQuery when eager-loading is set.
	Edges        ZenxiangLiyuRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ZenxiangLiyuRecordEdges holds the relations/edges for other nodes in the graph.
type ZenxiangLiyuRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Prize holds the value of the prize edge.
	Prize *ZenxiangLiyuPrize `json:"prize,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ZenxiangLiyuRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PrizeOrErr returns the Prize value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ZenxiangLiyuRecordEdges) PrizeOrErr() (*ZenxiangLiyuPrize, error) {
	if e.Prize != nil {
		return e.Prize, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: zenxiangliyuprize.Label}
	}
	return nil, &NotLoadedError{edge: "prize"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ZenxiangLiyuRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case zenxiangliyurecord.FieldConfigSnapshot:
			values[i] = new([]byte)
		case zenxiangliyurecord.FieldTicketAmount, zenxiangliyurecord.FieldRewardAmount, zenxiangliyurecord.FieldUserNetAmount, zenxiangliyurecord.FieldSystemRevenue, zenxiangliyurecord.FieldSystemExpense, zenxiangliyurecord.FieldSystemProfit, zenxiangliyurecord.FieldProbabilitySnapshot, zenxiangliyurecord.FieldBalanceBefore, zenxiangliyurecord.FieldBalanceAfterTicket, zenxiangliyurecord.FieldBalanceAfterReward:
			values[i] = new(sql.NullFloat64)
		case zenxiangliyurecord.FieldID, zenxiangliyurecord.FieldUserID, zenxiangliyurecord.FieldPrizeID:
			values[i] = new(sql.NullInt64)
		case zenxiangliyurecord.FieldRequestID, zenxiangliyurecord.FieldPrizeNameSnapshot:
			values[i] = new(sql.NullString)
		case zenxiangliyurecord.FieldPlayDate, zenxiangliyurecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ZenxiangLiyuRecord fields.
func (_m *ZenxiangLiyuRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case zenxiangliyurecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case zenxiangliyurecord.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case zenxiangliyurecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case zenxiangliyurecord.FieldPlayDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field play_date", values[i])
			} else if value.Valid {
				_m.PlayDate = value.Time
			}
		case zenxiangliyurecord.FieldTicketAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_amount", values[i])
			} else if value.Valid {
				_m.TicketAmount = value.Float64
			}
		case zenxiangliyurecord.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case zenxiangliyurecord.FieldUserNetAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field user_net_amount", values[i])
			} else if value.Valid {
				_m.UserNetAmount = value.Float64
			}
		case zenxiangliyurecord.FieldSystemRevenue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field system_revenue", values[i])
			} else if value.Valid {
				_m.SystemRevenue = value.Float64
			}
		case zenxiangliyurecord.FieldSystemExpense:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field system_expense", values[i])
			} else if value.Valid {
				_m.SystemExpense = value.Float64
			}
		case zenxiangliyurecord.FieldSystemProfit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field system_profit", values[i])
			} else if value.Valid {
				_m.SystemProfit = value.Float64
			}
		case zenxiangliyurecord.FieldPrizeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_id", values[i])
			} else if value.Valid {
				_m.PrizeID = new(int64)
				*_m.PrizeID = value.Int64
			}
		case zenxiangliyurecord.FieldPrizeNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_name_snapshot", values[i])
			} else if value.Valid {
				_m.PrizeNameSnapshot = value.String
			}
		case zenxiangliyurecord.FieldProbabilitySnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field probability_snapshot", values[i])
			} else if value.Valid {
				_m.ProbabilitySnapshot = value.Float64
			}
		case zenxiangliyurecord.FieldConfigSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigSnapshot); err != nil {
					return fmt.Errorf("unmarshal field config_snapshot: %w", err)
				}
			}
		case zenxiangliyurecord.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.Float64
			}
		case zenxiangliyurecord.FieldBalanceAfterTicket:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after_ticket", values[i])
			} else if value.Valid {
				_m.BalanceAfterTicket = value.Float64
			}
		case zenxiangliyurecord.FieldBalanceAfterReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after_reward", values[i])
			} else if value.Valid {
				_m.BalanceAfterReward = value.Float64
			}
		case zenxiangliyurecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ZenxiangLiyuRecord.
// This includes values selected through modifiers, order, etc.
func (_m *ZenxiangLiyuRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ZenxiangLiyuRecord entity.
func (_m *ZenxiangLiyuRecord) QueryUser() *UserQuery {
	return NewZenxiangLiyuRecordClient(_m.config).QueryUser(_m)
}

// QueryPrize queries the "prize" edge of the ZenxiangLiyuRecord entity.
func (_m *ZenxiangLiyuRecord) QueryPrize() *ZenxiangLiyuPrizeQuery {
	return NewZenxiangLiyuRecordClient(_m.config).QueryPrize(_m)
}

// Update returns a builder for updating this ZenxiangLiyuRecord.
// Note that you need to call ZenxiangLiyuRecord.Unwrap() before calling this method if this ZenxiangLiyuRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ZenxiangLiyuRecord) Update() *ZenxiangLiyuRecordUpdateOne {
	return NewZenxiangLiyuRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ZenxiangLiyuRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ZenxiangLiyuRecord) Unwrap() *ZenxiangLiyuRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ZenxiangLiyuRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ZenxiangLiyuRecord) String() string {
	var builder strings.Builder
	builder.WriteString("ZenxiangLiyuRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("play_date=")
	builder.WriteString(_m.PlayDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ticket_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketAmount))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("user_net_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserNetAmount))
	builder.WriteString(", ")
	builder.WriteString("system_revenue=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemRevenue))
	builder.WriteString(", ")
	builder.WriteString("system_expense=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemExpense))
	builder.WriteString(", ")
	builder.WriteString("system_profit=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemProfit))
	builder.WriteString(", ")
	if v := _m.PrizeID; v != nil {
		builder.WriteString("prize_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("prize_name_snapshot=")
	builder.WriteString(_m.PrizeNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("probability_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbabilitySnapshot))
	builder.WriteString(", ")
	builder.WriteString("config_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigSnapshot))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after_ticket=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfterTicket))
	builder.WriteString(", ")
	builder.WriteString("balance_after_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfterReward))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ZenxiangLiyuRecords is a parsable slice of ZenxiangLiyuRecord.
type ZenxiangLiyuRecords []*ZenxiangLiyuRecord
