// Code generated by ent, DO NOT EDIT.

package windsurfaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldAccount, v))
}

// PasswordEncrypted applies equality check predicate on the "password_encrypted" field. It's identical to PasswordEncryptedEQ.
func PasswordEncrypted(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldEnabled, v))
}

// MaintainedBy applies equality check predicate on the "maintained_by" field. It's identical to MaintainedByEQ.
func MaintainedBy(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldMaintainedBy, v))
}

// MaintainedAt applies equality check predicate on the "maintained_at" field. It's identical to MaintainedAtEQ.
func MaintainedAt(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldMaintainedAt, v))
}

// StatusUpdatedBy applies equality check predicate on the "status_updated_by" field. It's identical to StatusUpdatedByEQ.
func StatusUpdatedBy(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldStatusUpdatedBy, v))
}

// StatusUpdatedAt applies equality check predicate on the "status_updated_at" field. It's identical to StatusUpdatedAtEQ.
func StatusUpdatedAt(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldStatusUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldContainsFold(FieldAccount, v))
}

// PasswordEncryptedEQ applies the EQ predicate on the "password_encrypted" field.
func PasswordEncryptedEQ(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedNEQ applies the NEQ predicate on the "password_encrypted" field.
func PasswordEncryptedNEQ(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedIn applies the In predicate on the "password_encrypted" field.
func PasswordEncryptedIn(vs ...string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedNotIn applies the NotIn predicate on the "password_encrypted" field.
func PasswordEncryptedNotIn(vs ...string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedGT applies the GT predicate on the "password_encrypted" field.
func PasswordEncryptedGT(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedGTE applies the GTE predicate on the "password_encrypted" field.
func PasswordEncryptedGTE(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLT applies the LT predicate on the "password_encrypted" field.
func PasswordEncryptedLT(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLTE applies the LTE predicate on the "password_encrypted" field.
func PasswordEncryptedLTE(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContains applies the Contains predicate on the "password_encrypted" field.
func PasswordEncryptedContains(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldContains(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasPrefix applies the HasPrefix predicate on the "password_encrypted" field.
func PasswordEncryptedHasPrefix(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldHasPrefix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasSuffix applies the HasSuffix predicate on the "password_encrypted" field.
func PasswordEncryptedHasSuffix(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldHasSuffix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedEqualFold applies the EqualFold predicate on the "password_encrypted" field.
func PasswordEncryptedEqualFold(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEqualFold(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContainsFold applies the ContainsFold predicate on the "password_encrypted" field.
func PasswordEncryptedContainsFold(v string) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldContainsFold(FieldPasswordEncrypted, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldEnabled, v))
}

// MaintainedByEQ applies the EQ predicate on the "maintained_by" field.
func MaintainedByEQ(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldMaintainedBy, v))
}

// MaintainedByNEQ applies the NEQ predicate on the "maintained_by" field.
func MaintainedByNEQ(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldMaintainedBy, v))
}

// MaintainedByIn applies the In predicate on the "maintained_by" field.
func MaintainedByIn(vs ...int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldMaintainedBy, vs...))
}

// MaintainedByNotIn applies the NotIn predicate on the "maintained_by" field.
func MaintainedByNotIn(vs ...int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldMaintainedBy, vs...))
}

// MaintainedByGT applies the GT predicate on the "maintained_by" field.
func MaintainedByGT(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldMaintainedBy, v))
}

// MaintainedByGTE applies the GTE predicate on the "maintained_by" field.
func MaintainedByGTE(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldMaintainedBy, v))
}

// MaintainedByLT applies the LT predicate on the "maintained_by" field.
func MaintainedByLT(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldMaintainedBy, v))
}

// MaintainedByLTE applies the LTE predicate on the "maintained_by" field.
func MaintainedByLTE(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldMaintainedBy, v))
}

// MaintainedAtEQ applies the EQ predicate on the "maintained_at" field.
func MaintainedAtEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldMaintainedAt, v))
}

// MaintainedAtNEQ applies the NEQ predicate on the "maintained_at" field.
func MaintainedAtNEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldMaintainedAt, v))
}

// MaintainedAtIn applies the In predicate on the "maintained_at" field.
func MaintainedAtIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldMaintainedAt, vs...))
}

// MaintainedAtNotIn applies the NotIn predicate on the "maintained_at" field.
func MaintainedAtNotIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldMaintainedAt, vs...))
}

// MaintainedAtGT applies the GT predicate on the "maintained_at" field.
func MaintainedAtGT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldMaintainedAt, v))
}

// MaintainedAtGTE applies the GTE predicate on the "maintained_at" field.
func MaintainedAtGTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldMaintainedAt, v))
}

// MaintainedAtLT applies the LT predicate on the "maintained_at" field.
func MaintainedAtLT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldMaintainedAt, v))
}

// MaintainedAtLTE applies the LTE predicate on the "maintained_at" field.
func MaintainedAtLTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldMaintainedAt, v))
}

// StatusUpdatedByEQ applies the EQ predicate on the "status_updated_by" field.
func StatusUpdatedByEQ(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldStatusUpdatedBy, v))
}

// StatusUpdatedByNEQ applies the NEQ predicate on the "status_updated_by" field.
func StatusUpdatedByNEQ(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldStatusUpdatedBy, v))
}

// StatusUpdatedByIn applies the In predicate on the "status_updated_by" field.
func StatusUpdatedByIn(vs ...int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldStatusUpdatedBy, vs...))
}

// StatusUpdatedByNotIn applies the NotIn predicate on the "status_updated_by" field.
func StatusUpdatedByNotIn(vs ...int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldStatusUpdatedBy, vs...))
}

// StatusUpdatedByGT applies the GT predicate on the "status_updated_by" field.
func StatusUpdatedByGT(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldStatusUpdatedBy, v))
}

// StatusUpdatedByGTE applies the GTE predicate on the "status_updated_by" field.
func StatusUpdatedByGTE(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldStatusUpdatedBy, v))
}

// StatusUpdatedByLT applies the LT predicate on the "status_updated_by" field.
func StatusUpdatedByLT(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldStatusUpdatedBy, v))
}

// StatusUpdatedByLTE applies the LTE predicate on the "status_updated_by" field.
func StatusUpdatedByLTE(v int64) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldStatusUpdatedBy, v))
}

// StatusUpdatedByIsNil applies the IsNil predicate on the "status_updated_by" field.
func StatusUpdatedByIsNil() predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIsNull(FieldStatusUpdatedBy))
}

// StatusUpdatedByNotNil applies the NotNil predicate on the "status_updated_by" field.
func StatusUpdatedByNotNil() predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotNull(FieldStatusUpdatedBy))
}

// StatusUpdatedAtEQ applies the EQ predicate on the "status_updated_at" field.
func StatusUpdatedAtEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldEQ(FieldStatusUpdatedAt, v))
}

// StatusUpdatedAtNEQ applies the NEQ predicate on the "status_updated_at" field.
func StatusUpdatedAtNEQ(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNEQ(FieldStatusUpdatedAt, v))
}

// StatusUpdatedAtIn applies the In predicate on the "status_updated_at" field.
func StatusUpdatedAtIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIn(FieldStatusUpdatedAt, vs...))
}

// StatusUpdatedAtNotIn applies the NotIn predicate on the "status_updated_at" field.
func StatusUpdatedAtNotIn(vs ...time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotIn(FieldStatusUpdatedAt, vs...))
}

// StatusUpdatedAtGT applies the GT predicate on the "status_updated_at" field.
func StatusUpdatedAtGT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGT(FieldStatusUpdatedAt, v))
}

// StatusUpdatedAtGTE applies the GTE predicate on the "status_updated_at" field.
func StatusUpdatedAtGTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldGTE(FieldStatusUpdatedAt, v))
}

// StatusUpdatedAtLT applies the LT predicate on the "status_updated_at" field.
func StatusUpdatedAtLT(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLT(FieldStatusUpdatedAt, v))
}

// StatusUpdatedAtLTE applies the LTE predicate on the "status_updated_at" field.
func StatusUpdatedAtLTE(v time.Time) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldLTE(FieldStatusUpdatedAt, v))
}

// StatusUpdatedAtIsNil applies the IsNil predicate on the "status_updated_at" field.
func StatusUpdatedAtIsNil() predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldIsNull(FieldStatusUpdatedAt))
}

// StatusUpdatedAtNotNil applies the NotNil predicate on the "status_updated_at" field.
func StatusUpdatedAtNotNil() predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.FieldNotNull(FieldStatusUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WindsurfAccount) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WindsurfAccount) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WindsurfAccount) predicate.WindsurfAccount {
	return predicate.WindsurfAccount(sql.NotPredicates(p))
}
