// Code generated by ent, DO NOT EDIT.

package windsurfaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the windsurfaccount type in the database.
	Label = "windsurf_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldPasswordEncrypted holds the string denoting the password_encrypted field in the database.
	FieldPasswordEncrypted = "password_encrypted"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldMaintainedBy holds the string denoting the maintained_by field in the database.
	FieldMaintainedBy = "maintained_by"
	// FieldMaintainedAt holds the string denoting the maintained_at field in the database.
	FieldMaintainedAt = "maintained_at"
	// FieldStatusUpdatedBy holds the string denoting the status_updated_by field in the database.
	FieldStatusUpdatedBy = "status_updated_by"
	// FieldStatusUpdatedAt holds the string denoting the status_updated_at field in the database.
	FieldStatusUpdatedAt = "status_updated_at"
	// Table holds the table name of the windsurfaccount in the database.
	Table = "windsurf_accounts"
)

// Columns holds all SQL columns for windsurfaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccount,
	FieldPasswordEncrypted,
	FieldEnabled,
	FieldMaintainedBy,
	FieldMaintainedAt,
	FieldStatusUpdatedBy,
	FieldStatusUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AccountValidator is a validator for the "account" field. It is called by the builders before save.
	AccountValidator func(string) error
	// PasswordEncryptedValidator is a validator for the "password_encrypted" field. It is called by the builders before save.
	PasswordEncryptedValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the WindsurfAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// ByPasswordEncrypted orders the results by the password_encrypted field.
func ByPasswordEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordEncrypted, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByMaintainedBy orders the results by the maintained_by field.
func ByMaintainedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaintainedBy, opts...).ToFunc()
}

// ByMaintainedAt orders the results by the maintained_at field.
func ByMaintainedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaintainedAt, opts...).ToFunc()
}

// ByStatusUpdatedBy orders the results by the status_updated_by field.
func ByStatusUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusUpdatedBy, opts...).ToFunc()
}

// ByStatusUpdatedAt orders the results by the status_updated_at field.
func ByStatusUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusUpdatedAt, opts...).ToFunc()
}
