// Code generated by ent, DO NOT EDIT.

package openaiautoschedulerscoreevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldGroupID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldModel, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldEventType, v))
}

// ScoreBefore applies equality check predicate on the "score_before" field. It's identical to ScoreBeforeEQ.
func ScoreBefore(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldScoreBefore, v))
}

// ScoreAfter applies equality check predicate on the "score_after" field. It's identical to ScoreAfterEQ.
func ScoreAfter(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldScoreAfter, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldLatencyMs, v))
}

// TtfbMs applies equality check predicate on the "ttfb_ms" field. It's identical to TtfbMsEQ.
func TtfbMs(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldTtfbMs, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldStatusCode, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldAccountID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldGroupID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldContainsFold(FieldModel, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldContainsFold(FieldEventType, v))
}

// ScoreBeforeEQ applies the EQ predicate on the "score_before" field.
func ScoreBeforeEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldScoreBefore, v))
}

// ScoreBeforeNEQ applies the NEQ predicate on the "score_before" field.
func ScoreBeforeNEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldScoreBefore, v))
}

// ScoreBeforeIn applies the In predicate on the "score_before" field.
func ScoreBeforeIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldScoreBefore, vs...))
}

// ScoreBeforeNotIn applies the NotIn predicate on the "score_before" field.
func ScoreBeforeNotIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldScoreBefore, vs...))
}

// ScoreBeforeGT applies the GT predicate on the "score_before" field.
func ScoreBeforeGT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldScoreBefore, v))
}

// ScoreBeforeGTE applies the GTE predicate on the "score_before" field.
func ScoreBeforeGTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldScoreBefore, v))
}

// ScoreBeforeLT applies the LT predicate on the "score_before" field.
func ScoreBeforeLT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldScoreBefore, v))
}

// ScoreBeforeLTE applies the LTE predicate on the "score_before" field.
func ScoreBeforeLTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldScoreBefore, v))
}

// ScoreAfterEQ applies the EQ predicate on the "score_after" field.
func ScoreAfterEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldScoreAfter, v))
}

// ScoreAfterNEQ applies the NEQ predicate on the "score_after" field.
func ScoreAfterNEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldScoreAfter, v))
}

// ScoreAfterIn applies the In predicate on the "score_after" field.
func ScoreAfterIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldScoreAfter, vs...))
}

// ScoreAfterNotIn applies the NotIn predicate on the "score_after" field.
func ScoreAfterNotIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldScoreAfter, vs...))
}

// ScoreAfterGT applies the GT predicate on the "score_after" field.
func ScoreAfterGT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldScoreAfter, v))
}

// ScoreAfterGTE applies the GTE predicate on the "score_after" field.
func ScoreAfterGTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldScoreAfter, v))
}

// ScoreAfterLT applies the LT predicate on the "score_after" field.
func ScoreAfterLT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldScoreAfter, v))
}

// ScoreAfterLTE applies the LTE predicate on the "score_after" field.
func ScoreAfterLTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldScoreAfter, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotNull(FieldLatencyMs))
}

// TtfbMsEQ applies the EQ predicate on the "ttfb_ms" field.
func TtfbMsEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldTtfbMs, v))
}

// TtfbMsNEQ applies the NEQ predicate on the "ttfb_ms" field.
func TtfbMsNEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldTtfbMs, v))
}

// TtfbMsIn applies the In predicate on the "ttfb_ms" field.
func TtfbMsIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldTtfbMs, vs...))
}

// TtfbMsNotIn applies the NotIn predicate on the "ttfb_ms" field.
func TtfbMsNotIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldTtfbMs, vs...))
}

// TtfbMsGT applies the GT predicate on the "ttfb_ms" field.
func TtfbMsGT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldTtfbMs, v))
}

// TtfbMsGTE applies the GTE predicate on the "ttfb_ms" field.
func TtfbMsGTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldTtfbMs, v))
}

// TtfbMsLT applies the LT predicate on the "ttfb_ms" field.
func TtfbMsLT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldTtfbMs, v))
}

// TtfbMsLTE applies the LTE predicate on the "ttfb_ms" field.
func TtfbMsLTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldTtfbMs, v))
}

// TtfbMsIsNil applies the IsNil predicate on the "ttfb_ms" field.
func TtfbMsIsNil() predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIsNull(FieldTtfbMs))
}

// TtfbMsNotNil applies the NotNil predicate on the "ttfb_ms" field.
func TtfbMsNotNil() predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotNull(FieldTtfbMs))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldStatusCode, v))
}

// StatusCodeIsNil applies the IsNil predicate on the "status_code" field.
func StatusCodeIsNil() predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIsNull(FieldStatusCode))
}

// StatusCodeNotNil applies the NotNil predicate on the "status_code" field.
func StatusCodeNotNil() predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotNull(FieldStatusCode))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldContainsFold(FieldMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIAutoSchedulerScoreEvent) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIAutoSchedulerScoreEvent) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIAutoSchedulerScoreEvent) predicate.OpenAIAutoSchedulerScoreEvent {
	return predicate.OpenAIAutoSchedulerScoreEvent(sql.NotPredicates(p))
}
