// Code generated by ent, DO NOT EDIT.

package openaischedulerhealthstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaischedulerhealthstate type in the database.
	Label = "open_ai_scheduler_health_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldModelFamily holds the string denoting the model_family field in the database.
	FieldModelFamily = "model_family"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldTransport holds the string denoting the transport field in the database.
	FieldTransport = "transport"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldPredictedTtftMs holds the string denoting the predicted_ttft_ms field in the database.
	FieldPredictedTtftMs = "predicted_ttft_ms"
	// FieldErrorRate holds the string denoting the error_rate field in the database.
	FieldErrorRate = "error_rate"
	// FieldRateLimitedRate holds the string denoting the rate_limited_rate field in the database.
	FieldRateLimitedRate = "rate_limited_rate"
	// FieldServerErrorRate holds the string denoting the server_error_rate field in the database.
	FieldServerErrorRate = "server_error_rate"
	// FieldConsecutiveSlow holds the string denoting the consecutive_slow field in the database.
	FieldConsecutiveSlow = "consecutive_slow"
	// FieldConsecutiveError holds the string denoting the consecutive_error field in the database.
	FieldConsecutiveError = "consecutive_error"
	// FieldConsecutiveSuccess holds the string denoting the consecutive_success field in the database.
	FieldConsecutiveSuccess = "consecutive_success"
	// FieldRealSampleCount holds the string denoting the real_sample_count field in the database.
	FieldRealSampleCount = "real_sample_count"
	// FieldProbeSampleCount holds the string denoting the probe_sample_count field in the database.
	FieldProbeSampleCount = "probe_sample_count"
	// FieldLastRealAt holds the string denoting the last_real_at field in the database.
	FieldLastRealAt = "last_real_at"
	// FieldLastProbeAt holds the string denoting the last_probe_at field in the database.
	FieldLastProbeAt = "last_probe_at"
	// FieldCooldownUntil holds the string denoting the cooldown_until field in the database.
	FieldCooldownUntil = "cooldown_until"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the openaischedulerhealthstate in the database.
	Table = "openai_scheduler_health_states"
)

// Columns holds all SQL columns for openaischedulerhealthstate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldModelFamily,
	FieldEndpoint,
	FieldTransport,
	FieldState,
	FieldPredictedTtftMs,
	FieldErrorRate,
	FieldRateLimitedRate,
	FieldServerErrorRate,
	FieldConsecutiveSlow,
	FieldConsecutiveError,
	FieldConsecutiveSuccess,
	FieldRealSampleCount,
	FieldProbeSampleCount,
	FieldLastRealAt,
	FieldLastProbeAt,
	FieldCooldownUntil,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultModelFamily holds the default value on creation for the "model_family" field.
	DefaultModelFamily string
	// ModelFamilyValidator is a validator for the "model_family" field. It is called by the builders before save.
	ModelFamilyValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultTransport holds the default value on creation for the "transport" field.
	DefaultTransport string
	// TransportValidator is a validator for the "transport" field. It is called by the builders before save.
	TransportValidator func(string) error
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// StateValidator is a validator for the "state" field. It is called by the builders before save.
	StateValidator func(string) error
	// DefaultPredictedTtftMs holds the default value on creation for the "predicted_ttft_ms" field.
	DefaultPredictedTtftMs float64
	// DefaultErrorRate holds the default value on creation for the "error_rate" field.
	DefaultErrorRate float64
	// DefaultRateLimitedRate holds the default value on creation for the "rate_limited_rate" field.
	DefaultRateLimitedRate float64
	// DefaultServerErrorRate holds the default value on creation for the "server_error_rate" field.
	DefaultServerErrorRate float64
	// DefaultConsecutiveSlow holds the default value on creation for the "consecutive_slow" field.
	DefaultConsecutiveSlow int
	// DefaultConsecutiveError holds the default value on creation for the "consecutive_error" field.
	DefaultConsecutiveError int
	// DefaultConsecutiveSuccess holds the default value on creation for the "consecutive_success" field.
	DefaultConsecutiveSuccess int
	// DefaultRealSampleCount holds the default value on creation for the "real_sample_count" field.
	DefaultRealSampleCount int64
	// DefaultProbeSampleCount holds the default value on creation for the "probe_sample_count" field.
	DefaultProbeSampleCount int64
)

// OrderOption defines the ordering options for the OpenAISchedulerHealthState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByModelFamily orders the results by the model_family field.
func ByModelFamily(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelFamily, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByTransport orders the results by the transport field.
func ByTransport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransport, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByPredictedTtftMs orders the results by the predicted_ttft_ms field.
func ByPredictedTtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPredictedTtftMs, opts...).ToFunc()
}

// ByErrorRate orders the results by the error_rate field.
func ByErrorRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorRate, opts...).ToFunc()
}

// ByRateLimitedRate orders the results by the rate_limited_rate field.
func ByRateLimitedRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateLimitedRate, opts...).ToFunc()
}

// ByServerErrorRate orders the results by the server_error_rate field.
func ByServerErrorRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerErrorRate, opts...).ToFunc()
}

// ByConsecutiveSlow orders the results by the consecutive_slow field.
func ByConsecutiveSlow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveSlow, opts...).ToFunc()
}

// ByConsecutiveError orders the results by the consecutive_error field.
func ByConsecutiveError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveError, opts...).ToFunc()
}

// ByConsecutiveSuccess orders the results by the consecutive_success field.
func ByConsecutiveSuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveSuccess, opts...).ToFunc()
}

// ByRealSampleCount orders the results by the real_sample_count field.
func ByRealSampleCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealSampleCount, opts...).ToFunc()
}

// ByProbeSampleCount orders the results by the probe_sample_count field.
func ByProbeSampleCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeSampleCount, opts...).ToFunc()
}

// ByLastRealAt orders the results by the last_real_at field.
func ByLastRealAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRealAt, opts...).ToFunc()
}

// ByLastProbeAt orders the results by the last_probe_at field.
func ByLastProbeAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbeAt, opts...).ToFunc()
}

// ByCooldownUntil orders the results by the cooldown_until field.
func ByCooldownUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownUntil, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
