// Code generated by ent, DO NOT EDIT.

package zenxiangliyusetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the zenxiangliyusetting type in the database.
	Label = "zenxiang_liyu_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGlobalEnabled holds the string denoting the global_enabled field in the database.
	FieldGlobalEnabled = "global_enabled"
	// FieldTicketAmount holds the string denoting the ticket_amount field in the database.
	FieldTicketAmount = "ticket_amount"
	// FieldMinimumBalance holds the string denoting the minimum_balance field in the database.
	FieldMinimumBalance = "minimum_balance"
	// FieldDailyPlayLimit holds the string denoting the daily_play_limit field in the database.
	FieldDailyPlayLimit = "daily_play_limit"
	// FieldTicketUsageThreshold holds the string denoting the ticket_usage_threshold field in the database.
	FieldTicketUsageThreshold = "ticket_usage_threshold"
	// FieldDailyTicketLimit holds the string denoting the daily_ticket_limit field in the database.
	FieldDailyTicketLimit = "daily_ticket_limit"
	// FieldUnitSalePrice holds the string denoting the unit_sale_price field in the database.
	FieldUnitSalePrice = "unit_sale_price"
	// FieldUnitCostPrice holds the string denoting the unit_cost_price field in the database.
	FieldUnitCostPrice = "unit_cost_price"
	// Table holds the table name of the zenxiangliyusetting in the database.
	Table = "zenxiang_liyu_settings"
)

// Columns holds all SQL columns for zenxiangliyusetting fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGlobalEnabled,
	FieldTicketAmount,
	FieldMinimumBalance,
	FieldDailyPlayLimit,
	FieldTicketUsageThreshold,
	FieldDailyTicketLimit,
	FieldUnitSalePrice,
	FieldUnitCostPrice,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultGlobalEnabled holds the default value on creation for the "global_enabled" field.
	DefaultGlobalEnabled bool
	// DefaultTicketAmount holds the default value on creation for the "ticket_amount" field.
	DefaultTicketAmount float64
	// DefaultMinimumBalance holds the default value on creation for the "minimum_balance" field.
	DefaultMinimumBalance float64
	// DefaultDailyPlayLimit holds the default value on creation for the "daily_play_limit" field.
	DefaultDailyPlayLimit int
	// DefaultTicketUsageThreshold holds the default value on creation for the "ticket_usage_threshold" field.
	DefaultTicketUsageThreshold float64
	// DefaultDailyTicketLimit holds the default value on creation for the "daily_ticket_limit" field.
	DefaultDailyTicketLimit int
	// DefaultUnitSalePrice holds the default value on creation for the "unit_sale_price" field.
	DefaultUnitSalePrice float64
	// DefaultUnitCostPrice holds the default value on creation for the "unit_cost_price" field.
	DefaultUnitCostPrice float64
)

// OrderOption defines the ordering options for the ZenxiangLiyuSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGlobalEnabled orders the results by the global_enabled field.
func ByGlobalEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGlobalEnabled, opts...).ToFunc()
}

// ByTicketAmount orders the results by the ticket_amount field.
func ByTicketAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketAmount, opts...).ToFunc()
}

// ByMinimumBalance orders the results by the minimum_balance field.
func ByMinimumBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinimumBalance, opts...).ToFunc()
}

// ByDailyPlayLimit orders the results by the daily_play_limit field.
func ByDailyPlayLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyPlayLimit, opts...).ToFunc()
}

// ByTicketUsageThreshold orders the results by the ticket_usage_threshold field.
func ByTicketUsageThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketUsageThreshold, opts...).ToFunc()
}

// ByDailyTicketLimit orders the results by the daily_ticket_limit field.
func ByDailyTicketLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyTicketLimit, opts...).ToFunc()
}

// ByUnitSalePrice orders the results by the unit_sale_price field.
func ByUnitSalePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitSalePrice, opts...).ToFunc()
}

// ByUnitCostPrice orders the results by the unit_cost_price field.
func ByUnitCostPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitCostPrice, opts...).ToFunc()
}
